<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Repositories\AssetClassRepository;
use App\Repositories\AssetRepository;

class AcaoSeeder extends Seeder
{
    protected $assetClassRepository;
    protected $assetRepository;

    public function __construct(AssetClassRepository $assetClassRepository, AssetRepository $assetRepository)
    {
        $this->assetClassRepository = $assetClassRepository;
        $this->assetRepository = $assetRepository;
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $assetClass = $this->assetClassRepository->getBySlug('acoes');

        foreach ($this->getData() as $data) {
            $asset = $this->assetRepository->getAssetByTicker($data['ticker']);

            if ($asset) {
                continue;
            }

            $this->assetRepository->createAsset([
                'asset_class_id' => $assetClass->id,
                'ticker' => $data['ticker']
            ]);
        }
    }

    public function getData(): array
    {
        return [
            ['name' => 'Hapvida', 'ticker' => 'HAPV3'],
            ['name' => 'Magazine Luiza', 'ticker' => 'MGLU3'],
            ['name' => 'Petrobras', 'ticker' => 'PETR4'],
            ['name' => 'Americanas', 'ticker' => 'AMER3'],
            ['name' => 'Cielo', 'ticker' => 'CIEL3'],
            ['name' => 'Lojas Renner', 'ticker' => 'LREN3'],
            ['name' => 'Cogna', 'ticker' => 'COGN3'],
            ['name' => 'BRF', 'ticker' => 'BRFS3'],
            ['name' => 'B3', 'ticker' => 'B3SA3'],
            ['name' => 'Ambev', 'ticker' => 'ABEV3'],
            ['name' => 'CVC', 'ticker' => 'CVCB3'],
            ['name' => 'Banco Bradesco', 'ticker' => 'BBDC4'],
            ['name' => 'Vale', 'ticker' => 'VALE3'],
            ['name' => 'Itaú Unibanco', 'ticker' => 'ITUB4'],
            ['name' => 'Natura', 'ticker' => 'NTCO3'],
            ['name' => 'MRV', 'ticker' => 'MRVE3'],
            ['name' => 'Assaí', 'ticker' => 'ASAI3'],
            ['name' => 'Ânima Educação', 'ticker' => 'ANIM3'],
            ['name' => 'Infracommerce', 'ticker' => 'IFCM3'],
            ['name' => 'PetroRio', 'ticker' => 'PRIO3'],
            ['name' => 'Grupo Soma', 'ticker' => 'SOMA3'],
            ['name' => 'Raízen', 'ticker' => 'RAIZ4'],
            ['name' => 'Localiza', 'ticker' => 'RENT3'],
            ['name' => 'Itaúsa', 'ticker' => 'ITSA4'],
            ['name' => 'Petz', 'ticker' => 'PETZ3'],
            ['name' => 'Grupo CCR', 'ticker' => 'CCRO3'],
            ['name' => 'Rumo', 'ticker' => 'RAIL3'],
            ['name' => 'Sequoia Logística', 'ticker' => 'SEQL3'],
            ['name' => 'Grupo Pão de Açúcar', 'ticker' => 'PCAR3'],
            ['name' => 'CSN Mineração', 'ticker' => 'CMIN3'],
            ['name' => 'Gerdau', 'ticker' => 'GGBR4'],
            ['name' => 'Petrobras', 'ticker' => 'PETR3'],
            ['name' => 'RaiaDrogasil', 'ticker' => 'RADL3'],
            ['name' => 'Hidrovias do Brasil', 'ticker' => 'HBSA3'],
            ['name' => 'Eneva', 'ticker' => 'ENEV3'],
            ['name' => 'Minerva', 'ticker' => 'BEEF3'],
            ['name' => 'Marfrig', 'ticker' => 'MRFG3'],
            ['name' => 'JBS', 'ticker' => 'JBSS3'],
            ['name' => 'Azul', 'ticker' => 'AZUL4'],
            ['name' => 'Metalúrgica Gerdau', 'ticker' => 'GOAU4'],
            ['name' => 'Cosan', 'ticker' => 'CSAN3'],
            ['name' => 'Carrefour Brasil', 'ticker' => 'CRFB3'],
            ['name' => 'Usiminas', 'ticker' => 'USIM5'],
            ['name' => 'Eletrobras', 'ticker' => 'ELET3'],
            ['name' => 'Cyrela', 'ticker' => 'CYRE3'],
            ['name' => 'GOL', 'ticker' => 'GOLL4'],
            ['name' => 'CEMIG', 'ticker' => 'CMIG4'],
            ['name' => 'Rede D\'Or', 'ticker' => 'RDOR3'],
            ['name' => 'TIM', 'ticker' => 'TIMS3'],
            ['name' => 'Grupo Vamos', 'ticker' => 'VAMO3'],
            ['name' => 'Qualicorp', 'ticker' => 'QUAL3'],
            ['name' => '3R Petroleum', 'ticker' => 'RRRP3'],
            ['name' => 'Aeris Energy', 'ticker' => 'AERI3'],
            ['name' => 'Locaweb', 'ticker' => 'LWSA3'],
            ['name' => 'Banco Bradesco', 'ticker' => 'BBDC3'],
            ['name' => 'Banco do Brasil', 'ticker' => 'BBAS3'],
            ['name' => 'Suzano', 'ticker' => 'SUZB3'],
            ['name' => 'CPFL Energia', 'ticker' => 'CPFE3'],
            ['name' => 'WEG', 'ticker' => 'WEGE3'],
            ['name' => 'Vibra Energia', 'ticker' => 'VBBR3'],
            ['name' => 'BB Seguridade', 'ticker' => 'BBSE3'],
            ['name' => 'Ultrapar', 'ticker' => 'UGPA3'],
            ['name' => 'EcoRodovias', 'ticker' => 'ECOR3'],
            ['name' => 'Embraer', 'ticker' => 'EMBR3'],
            ['name' => 'JHSF', 'ticker' => 'JHSF3'],
            ['name' => 'Multilaser', 'ticker' => 'MLAS3'],
            ['name' => 'Equatorial Energia', 'ticker' => 'EQTL3'],
            ['name' => 'Multiplan', 'ticker' => 'MULT3'],
            ['name' => 'CBA', 'ticker' => 'CBAV3'],
            ['name' => 'C&A', 'ticker' => 'CEAB3'],
            ['name' => 'Copel', 'ticker' => 'CPLE3'],
            ['name' => 'Copel', 'ticker' => 'CPLE5'],
            ['name' => 'Copel', 'ticker' => 'CPLE6'],
            ['name' => 'Copel', 'ticker' => 'CPLE11'],
            ['name' => 'Construtora Tenda', 'ticker' => 'TEND3'],
            ['name' => 'Aliansce Sonae', 'ticker' => 'ALSO3'],
            ['name' => 'Santos Brasil', 'ticker' => 'STBP3'],
            ['name' => 'Sabesp', 'ticker' => 'SBSP3'],
            ['name' => 'Totvs', 'ticker' => 'TOTS3'],
            ['name' => 'PetroRecôncavo', 'ticker' => 'RECV3'],
            ['name' => 'Direcional', 'ticker' => 'DIRR3'],
            ['name' => 'Movida', 'ticker' => 'MOVI3'],
            ['name' => 'Oi', 'ticker' => 'OIBR3'],
            ['name' => 'Siderúrgica Nacional', 'ticker' => 'CSNA3'],
            ['name' => 'YDUQS', 'ticker' => 'YDUQ3'],
            ['name' => 'Caixa Seguridade', 'ticker' => 'CXSE3'],
            ['name' => 'Dexco', 'ticker' => 'DXCO3'],
            ['name' => 'Bradespar', 'ticker' => 'BRAP4'],
            ['name' => 'Recrusul', 'ticker' => 'RCSL4'],
            ['name' => 'Grupo SBF', 'ticker' => 'SBFG3'],
            ['name' => 'Grupo Mateus', 'ticker' => 'GMAT3'],
            ['name' => 'Eletrobras', 'ticker' => 'ELET6'],
            ['name' => 'Marcopolo', 'ticker' => 'POMO4'],
            ['name' => 'Vivo', 'ticker' => 'VIVT3'],
            ['name' => 'Cury', 'ticker' => 'CURY3'],
            ['name' => 'IRB Brasil RE', 'ticker' => 'IRBR3'],
            ['name' => 'Lojas Marisa', 'ticker' => 'AMAR3'],
            ['name' => 'Simpar', 'ticker' => 'SIMH3'],
            ['name' => 'Azevedo & Travassos', 'ticker' => 'AZEV4'],
            ['name' => 'Lojas Quero-Quero', 'ticker' => 'LJQQ3'],
            ['name' => 'Alpargatas', 'ticker' => 'ALPA4'],
            ['name' => 'Ser Educacional', 'ticker' => 'SEER3'],
            ['name' => 'Braskem', 'ticker' => 'BRKM5'],
            ['name' => 'Smart Fit', 'ticker' => 'SMFT3'],
            ['name' => 'EZTEC', 'ticker' => 'EZTC3'],
            ['name' => 'M. Dias Branco', 'ticker' => 'MDIA3'],
            ['name' => 'Hypera', 'ticker' => 'HYPE3'],
            ['name' => 'AES Brasil', 'ticker' => 'AESB3'],
            ['name' => 'Positivo', 'ticker' => 'POSI3'],
            ['name' => 'Gafisa', 'ticker' => 'GFSA3'],
            ['name' => 'Fleury', 'ticker' => 'FLRY3'],
            ['name' => 'Intelbras', 'ticker' => 'INTB3'],
            ['name' => 'Randon', 'ticker' => 'RAPT4'],
            ['name' => 'Arezzo', 'ticker' => 'ARZZ3'],
            ['name' => 'São Martinho', 'ticker' => 'SMTO3'],
            ['name' => 'Vivara', 'ticker' => 'VIVA3'],
            ['name' => 'Méliuz', 'ticker' => 'CASH3'],
            ['name' => 'Enauta', 'ticker' => 'ENAT3'],
            ['name' => 'Grendene', 'ticker' => 'GRND3'],
            ['name' => 'GPS', 'ticker' => 'GGPS3'],
            ['name' => 'COPASA', 'ticker' => 'CSMG3'],
            ['name' => 'Banco Pan', 'ticker' => 'BPAN4'],
            ['name' => 'VTRM ENERGIA PARTICIPAÇÕES S.A.', 'ticker' => 'AURE3'],
            ['name' => 'Klabin', 'ticker' => 'KLBN4'],
            ['name' => 'Klabin', 'ticker' => 'KLBN3'],
            ['name' => 'Klabin', 'ticker' => 'KLBN11'],
            ['name' => 'Espaçolaser', 'ticker' => 'ESPA3'],
            ['name' => 'Oncoclínicas', 'ticker' => 'ONCO3'],
            ['name' => 'Azevedo & Travassos', 'ticker' => 'AZEV3'],
            ['name' => 'Guararapes', 'ticker' => 'GUAR3'],
            ['name' => 'Odontoprev', 'ticker' => 'ODPV3'],
            ['name' => 'Zamp', 'ticker' => 'ZAMP3'],
            ['name' => 'Light', 'ticker' => 'LIGT3'],
            ['name' => 'Engie', 'ticker' => 'EGIE3'],
            ['name' => 'Plano&Plano', 'ticker' => 'PLPL3'],
            ['name' => 'Recrusul', 'ticker' => 'RCSL3'],
            ['name' => 'Pague Menos', 'ticker' => 'PGMN3'],
            ['name' => 'Iochpe-Maxion', 'ticker' => 'MYPK3'],
            ['name' => 'Kepler Weber', 'ticker' => 'KEPL3'],
            ['name' => 'Camil Alimentos', 'ticker' => 'CAML3'],
            ['name' => 'Banrisul', 'ticker' => 'BRSR6'],
            ['name' => 'Bemobi', 'ticker' => 'BMOB3'],
            ['name' => 'Kora Saúde', 'ticker' => 'KRSA3'],
            ['name' => 'GetNinjas', 'ticker' => 'NINJ3'],
            ['name' => 'Indústrias ROMI', 'ticker' => 'ROMI3'],
            ['name' => 'Porto Seguro', 'ticker' => 'PSSA3'],
            ['name' => 'Even', 'ticker' => 'EVEN3'],
            ['name' => 'Westwing', 'ticker' => 'WEST3'],
            ['name' => 'Mitre Realty', 'ticker' => 'MTRE3'],
            ['name' => 'SLC Agrícola', 'ticker' => 'SLCE3'],
            ['name' => 'OMEGA ENERGIA S.A.', 'ticker' => 'MEGA3'],
            ['name' => 'Sinqia', 'ticker' => 'SQIA3'],
            ['name' => 'Neoenergia', 'ticker' => 'NEOE3'],
            ['name' => '3tentos', 'ticker' => 'TTEN3'],
            ['name' => 'Mobly', 'ticker' => 'MBLY3'],
            ['name' => 'Traders Club', 'ticker' => 'TRAD3'],
            ['name' => 'Dasa', 'ticker' => 'DASA3'],
            ['name' => 'Wilson Sons', 'ticker' => 'PORT3'],
            ['name' => 'IMC Alimentação', 'ticker' => 'MEAL3'],
            ['name' => 'Wiz Soluções', 'ticker' => 'WIZC3'],
            ['name' => 'Portobello', 'ticker' => 'PTBL3'],
            ['name' => 'Jalles Machado', 'ticker' => 'JALL3'],
            ['name' => 'Trisul', 'ticker' => 'TRIS3'],
            ['name' => 'Armac', 'ticker' => 'ARML3'],
            ['name' => 'BrasilAgro', 'ticker' => 'AGRO3'],
            ['name' => 'Irani', 'ticker' => 'RANI3'],
            ['name' => 'Mills', 'ticker' => 'MILS3'],
            ['name' => 'Banco BMG', 'ticker' => 'BMGB4'],
            ['name' => 'Banco ABC Brasil', 'ticker' => 'ABCB4'],
            ['name' => 'Ambipar', 'ticker' => 'AMBP3'],
            ['name' => 'Valid', 'ticker' => 'VLID3'],
            ['name' => 'Tupy', 'ticker' => 'TUPY3'],
            ['name' => 'Enjoei', 'ticker' => 'ENJU3'],
            ['name' => 'Eternit', 'ticker' => 'ETER3'],
            ['name' => 'Fras-le', 'ticker' => 'FRAS3'],
            ['name' => 'OceanPact', 'ticker' => 'OPCT3'],
            ['name' => 'Viveo', 'ticker' => 'VVEO3'],
            ['name' => 'Helbor', 'ticker' => 'HBOR3'],
            ['name' => 'Lupatech', 'ticker' => 'LUPA3'],
            ['name' => 'Blau Farmacêutica', 'ticker' => 'BLAU3'],
            ['name' => 'Brisanet', 'ticker' => 'BRIT3'],
            ['name' => 'Springs', 'ticker' => 'SGPS3'],
            ['name' => 'Technos', 'ticker' => 'TECN3'],
            ['name' => 'Lavvi Incorporadora', 'ticker' => 'LAVV3'],
            ['name' => 'Vulcabras', 'ticker' => 'VULC3'],
            ['name' => 'Time For Fun', 'ticker' => 'SHOW3'],
            ['name' => 'Itaú Unibanco', 'ticker' => 'ITUB3'],
            ['name' => 'Moura Dubeux', 'ticker' => 'MDNE3'],
            ['name' => 'Boa Safra Sementes', 'ticker' => 'SOJA3'],
            ['name' => 'Schulz', 'ticker' => 'SHUL4'],
            ['name' => 'PINE', 'ticker' => 'PINE4'],
            ['name' => 'Dimed', 'ticker' => 'PNVL3'],
            ['name' => 'Mater Dei', 'ticker' => 'MATD3'],
            ['name' => 'LOG CP', 'ticker' => 'LOGG3'],
            ['name' => 'Taurus', 'ticker' => 'TASA4'],
            ['name' => 'Neogrid', 'ticker' => 'NGRD3'],
            ['name' => 'Lopes', 'ticker' => 'LPSB3'],
            ['name' => 'Cruzeiro do Sul Educacional', 'ticker' => 'CSED3'],
            ['name' => 'Mahle Metal Leve', 'ticker' => 'LEVE3'],
            ['name' => 'Viver', 'ticker' => 'VIVR3'],
            ['name' => 'Orizon', 'ticker' => 'ORVR3'],
            ['name' => 'SYN', 'ticker' => 'SYNE3'],
            ['name' => 'HBR Realty', 'ticker' => 'HBRE3'],
            ['name' => 'Taesa', 'ticker' => 'TAEE3'],
            ['name' => 'Taesa', 'ticker' => 'TAEE4'],
            ['name' => 'Taesa', 'ticker' => 'TAEE11'],
            ['name' => 'Sanepar', 'ticker' => 'SAPR3'],
            ['name' => 'Sanepar', 'ticker' => 'SAPR4'],
            ['name' => 'Sanepar', 'ticker' => 'SAPR11'],
            ['name' => 'Usiminas', 'ticker' => 'USIM3'],
            ['name' => 'Unipar', 'ticker' => 'UNIP6'],
            ['name' => 'Vittia', 'ticker' => 'VITT3'],
            ['name' => 'Banco Santander', 'ticker' => 'SANB3'],
            ['name' => 'Banco Santander', 'ticker' => 'SANB4'],
            ['name' => 'Banco Santander', 'ticker' => 'SANB11'],
            ['name' => 'Unifique', 'ticker' => 'FIQE3'],
            ['name' => 'Alliança', 'ticker' => 'AALR3'],
            ['name' => 'Priner', 'ticker' => 'PRNR3'],
            ['name' => 'Ferbasa', 'ticker' => 'FESA4'],
            ['name' => 'ClearSale', 'ticker' => 'CLSA3'],
            ['name' => 'CEMIG', 'ticker' => 'CMIG3'],
            ['name' => 'Desktop', 'ticker' => 'DESK3'],
            ['name' => 'Renova Energia', 'ticker' => 'RNEW3'],
            ['name' => 'Renova Energia', 'ticker' => 'RNEW4'],
            ['name' => 'Renova Energia', 'ticker' => 'RNEW11'],
            ['name' => 'Dexxos', 'ticker' => 'DEXP3'],
            ['name' => 'Saraiva', 'ticker' => 'SLED4'],
            ['name' => 'Track & Field', 'ticker' => 'TFCO4'],
            ['name' => 'Atma', 'ticker' => 'ATMP3'],
            ['name' => 'Tegma', 'ticker' => 'TGMA3'],
            ['name' => 'Melnick', 'ticker' => 'MELK3'],
            ['name' => 'Inepar', 'ticker' => 'INEP3'],
            ['name' => 'Tecnisa', 'ticker' => 'TCSA3'],
            ['name' => 'Estapar', 'ticker' => 'ALPK3'],
            ['name' => 'Terra Santa', 'ticker' => 'LAND3'],
            ['name' => 'JSL', 'ticker' => 'JSLG3'],
            ['name' => 'Haga', 'ticker' => 'HAGA4'],
            ['name' => 'Santanense', 'ticker' => 'CTSA4'],
            ['name' => 'AgroGalaxy', 'ticker' => 'AGXY3'],
            ['name' => 'Coteminas', 'ticker' => 'CTNM4'],
            ['name' => 'Profarma', 'ticker' => 'PFRM3'],
            ['name' => 'Bombril', 'ticker' => 'BOBR4'],
            ['name' => 'Log-In', 'ticker' => 'LOGN3'],
            ['name' => 'PDG Realty', 'ticker' => 'PDGR3'],
            ['name' => 'Eletromidia', 'ticker' => 'ELMD3'],
            ['name' => 'Eucatex', 'ticker' => 'EUCA4'],
            ['name' => 'Marcopolo', 'ticker' => 'POMO3'],
            ['name' => 'Inepar', 'ticker' => 'INEP4'],
            ['name' => 'Itaúsa', 'ticker' => 'ITSA3'],
            ['name' => 'Iguatemi', 'ticker' => 'IGTI3'],
            ['name' => 'Iguatemi', 'ticker' => 'IGTI4'],
            ['name' => 'Iguatemi', 'ticker' => 'IGTI11'],
            ['name' => 'Jereissati Participações', 'ticker' => 'IGTI3'],
            ['name' => 'Jereissati Participações', 'ticker' => 'IGTI4'],
            ['name' => 'Jereissati Participações', 'ticker' => 'IGTI11'],
            ['name' => 'Dotz', 'ticker' => 'DOTZ3'],
            ['name' => 'Gerdau', 'ticker' => 'GGBR3'],
            ['name' => 'Grazziotin', 'ticker' => 'CGRA4'],
            ['name' => 'CSU Cardsystem', 'ticker' => 'CSUD3'],
            ['name' => 'Padtec', 'ticker' => 'PDTC3'],
            ['name' => 'Alper', 'ticker' => 'APER3'],
            ['name' => 'João Fortes', 'ticker' => 'JFEN3'],
            ['name' => 'Rossi Residencial', 'ticker' => 'RSID3'],
            ['name' => 'Metalúrgica Gerdau', 'ticker' => 'GOAU3'],
            ['name' => 'Unicasa', 'ticker' => 'UCAS3'],
            ['name' => 'WDC Networks', 'ticker' => 'LVTC3'],
            ['name' => 'Bradespar', 'ticker' => 'BRAP3'],
            ['name' => 'Cambuci', 'ticker' => 'CAMB3'],
            ['name' => 'Santanense', 'ticker' => 'CTSA3'],
            ['name' => 'Biomm', 'ticker' => 'BIOM3'],
            ['name' => 'Allied', 'ticker' => 'ALLD3'],
            ['name' => 'Alupar', 'ticker' => 'ALUP3'],
            ['name' => 'Alupar', 'ticker' => 'ALUP4'],
            ['name' => 'Alupar', 'ticker' => 'ALUP11'],
            ['name' => 'Coelce', 'ticker' => 'COCE5'],
            ['name' => 'RNI', 'ticker' => 'RDNI3'],
            ['name' => 'D1000 Varejo Farma', 'ticker' => 'DMVF3'],
            ['name' => 'Pettenati', 'ticker' => 'PTNT4'],
            ['name' => 'Banestes', 'ticker' => 'BEES3'],
            ['name' => 'Fertilizantes Heringer', 'ticker' => 'FHER3'],
            ['name' => 'OSX Brasil', 'ticker' => 'OSXB3'],
            ['name' => 'LE LIS BLANC', 'ticker' => 'VSTE3'],
            ['name' => 'Paranapanema', 'ticker' => 'PMAM3'],
            ['name' => 'São Carlos', 'ticker' => 'SCAR3'],
            ['name' => 'Braskem', 'ticker' => 'BRKM3'],
            ['name' => 'Triunfo', 'ticker' => 'TPIS3'],
            ['name' => 'Refinaria de Manguinhos', 'ticker' => 'RPMG3'],
            ['name' => 'Pomi Frutas', 'ticker' => 'FRTA3'],
            ['name' => 'CEB', 'ticker' => 'CEBR6'],
            ['name' => 'Oi', 'ticker' => 'OIBR4'],
            ['name' => 'Rede Energia', 'ticker' => 'REDE3'],
            ['name' => 'ATOM', 'ticker' => 'ATOM3'],
            ['name' => 'CEB', 'ticker' => 'CEBR3'],
            ['name' => 'Equatorial Energia Pará', 'ticker' => 'EQPA3'],
            ['name' => 'Banestes', 'ticker' => 'BEES4'],
            ['name' => 'Josapar', 'ticker' => 'JOPA3'],
            ['name' => 'Minupar', 'ticker' => 'MNPR3'],
            ['name' => 'METISA', 'ticker' => 'MTSA4'],
            ['name' => 'Tronox Pigmentos', 'ticker' => 'CRPG6'],
            ['name' => 'Nutriplant', 'ticker' => 'NUTR3'],
            ['name' => 'Taurus', 'ticker' => 'TASA3'],
            ['name' => 'Unipar', 'ticker' => 'UNIP3'],
            ['name' => 'Celesc', 'ticker' => 'CLSC4'],
            ['name' => 'Mangels', 'ticker' => 'MGEL4'],
            ['name' => 'Randon', 'ticker' => 'RAPT3'],
            ['name' => 'Wetzel', 'ticker' => 'MWET4'],
            ['name' => 'Energisa', 'ticker' => 'ENGI3'],
            ['name' => 'Energisa', 'ticker' => 'ENGI4'],
            ['name' => 'Energisa', 'ticker' => 'ENGI11'],
            ['name' => 'Electro Aço Altona', 'ticker' => 'EALT4'],
            ['name' => 'Haga', 'ticker' => 'HAGA3'],
            ['name' => 'Afluente T', 'ticker' => 'AFLT3'],
            ['name' => 'Grazziotin', 'ticker' => 'CGRA3'],
            ['name' => 'Ourofino Saúde Animal', 'ticker' => 'OFSA3'],
            ['name' => 'BR Properties', 'ticker' => 'BRPR3'],
            ['name' => 'Consórcio Alfa', 'ticker' => 'BRGE12'],
            ['name' => 'Tronox Pigmentos', 'ticker' => 'CRPG5'],
            ['name' => 'Banco Mercantil do Brasil', 'ticker' => 'BMEB4'],
            ['name' => 'Brasil Brokers', 'ticker' => 'NEXP3'],
            ['name' => 'Whirlpool', 'ticker' => 'WHRL4'],
            ['name' => 'Banco BTG Pactual', 'ticker' => 'BPAC3'],
            ['name' => 'Banco BTG Pactual', 'ticker' => 'BPAC5'],
            ['name' => 'Banco BTG Pactual', 'ticker' => 'BPAC11'],
            ['name' => 'Energisa MT', 'ticker' => 'ENMT3'],
            ['name' => 'Metalúrgica Riosulense', 'ticker' => 'RSUL4'],
            ['name' => 'EMAE', 'ticker' => 'EMAE4'],
            ['name' => 'Banese', 'ticker' => 'BGIP4'],
            ['name' => 'WLM', 'ticker' => 'WLMM4'],
            ['name' => 'Transmissão Paulista', 'ticker' => 'TRPL3'],
            ['name' => 'Alfa Investimento', 'ticker' => 'BRIV4'],
            ['name' => 'Sansuy', 'ticker' => 'SNSY5'],
            ['name' => 'Cedro Têxtil', 'ticker' => 'CEDO4'],
            ['name' => 'Dexxos', 'ticker' => 'DEXP4'],
            ['name' => 'Banrisul', 'ticker' => 'BRSR3'],
            ['name' => 'Eucatex', 'ticker' => 'EUCA3'],
            ['name' => 'Banco da Amazônia', 'ticker' => 'BAZA3'],
            ['name' => 'CEB', 'ticker' => 'CEBR5'],
            ['name' => 'Coteminas', 'ticker' => 'CTNM3'],
            ['name' => 'Saraiva', 'ticker' => 'SLED3'],
            ['name' => 'Hotéis Othon', 'ticker' => 'HOOT4'],
            ['name' => 'Whirlpool', 'ticker' => 'WHRL3'],
            ['name' => 'Telebras', 'ticker' => 'TELB4'],
            ['name' => 'Alfa Financeira', 'ticker' => 'CRIV3'],
            ['name' => 'Alpargatas', 'ticker' => 'ALPA3'],
            ['name' => 'Pettenati', 'ticker' => 'PTNT3'],
            ['name' => 'Comgás', 'ticker' => 'CGAS5'],
            ['name' => 'Banco de Brasília', 'ticker' => 'BSLI4'],
            ['name' => 'Bahema', 'ticker' => 'BAHI3'],
            ['name' => 'Electro Aço Altona', 'ticker' => 'EALT3'],
            ['name' => 'Sansuy', 'ticker' => 'SNSY3'],
            ['name' => 'Alphaville', 'ticker' => 'AVLL3'],
            ['name' => 'Eletropar', 'ticker' => 'LIPR3'],
            ['name' => 'Participações Aliança da Bahia', 'ticker' => 'PEAB3'],
            ['name' => 'Cedro Têxtil', 'ticker' => 'CEDO3'],
            ['name' => 'Equatorial Energia Pará', 'ticker' => 'EQPA5'],
            ['name' => 'Unipar', 'ticker' => 'UNIP5'],
            ['name' => 'Habitasul', 'ticker' => 'HBTS5'],
            ['name' => 'Mundial', 'ticker' => 'MNDL3'],
            ['name' => 'COSERN', 'ticker' => 'CSRN3'],
            ['name' => 'Baumer', 'ticker' => 'BALM4'],
            ['name' => 'Döhler', 'ticker' => 'DOHL4'],
            ['name' => 'Sondotécnica', 'ticker' => 'SOND5'],
            ['name' => 'Banese', 'ticker' => 'BGIP3'],
            ['name' => 'Rio Paranapanema Energia', 'ticker' => 'GEPA4'],
            ['name' => 'Telebras', 'ticker' => 'TELB3'],
            ['name' => 'Banco de Brasília', 'ticker' => 'BSLI3'],
            ['name' => 'Baumer', 'ticker' => 'BALM3'],
            ['name' => 'Alfa Holdings', 'ticker' => 'RPAD3'],
            ['name' => 'Hercules', 'ticker' => 'HETA4'],
            ['name' => 'Monark', 'ticker' => 'BMKS3'],
            ['name' => 'EPAR3', 'ticker' => 'EPAR3'],
            ['name' => 'Elektro', 'ticker' => 'EKTR4'],
            ['name' => 'Teka', 'ticker' => 'TEKA4'],
            ['name' => 'Ferbasa', 'ticker' => 'FESA3'],
            ['name' => 'Banco do Nordeste', 'ticker' => 'BNBR3'],
            ['name' => 'Alfa Investimento', 'ticker' => 'BRIV3'],
            ['name' => 'CEEE D', 'ticker' => 'CEED3'],
            ['name' => 'Consórcio Alfa', 'ticker' => 'BRGE11'],
            ['name' => 'Estrela', 'ticker' => 'ESTR4'],
            ['name' => 'CEEE D', 'ticker' => 'CEED4'],
            ['name' => 'Panatlântica', 'ticker' => 'PATI3'],
            ['name' => 'Banco Mercantil de Investimentos', 'ticker' => 'BMIN4'],
            ['name' => 'Consórcio Alfa', 'ticker' => 'BRGE3'],
            ['name' => 'Alfa Financeira', 'ticker' => 'CRIV4'],
            ['name' => 'Mercantil do Brasil Financeira', 'ticker' => 'MERC4'],
            ['name' => 'COELBA', 'ticker' => 'CEEB3'],
            ['name' => 'Banrisul', 'ticker' => 'BRSR5'],
            ['name' => 'Consórcio Alfa', 'ticker' => 'BRGE6'],
            ['name' => 'Consórcio Alfa', 'ticker' => 'BRGE5'],
            ['name' => 'Equatorial Energia Pará', 'ticker' => 'EQPA6'],
            ['name' => 'Döhler', 'ticker' => 'DOHL3'],
            ['name' => 'Equatorial Maranhão', 'ticker' => 'EQMA3B'],
            ['name' => 'Excelsior', 'ticker' => 'BAUH4'],
            ['name' => 'Tekno', 'ticker' => 'TKNO4'],
            ['name' => 'Metalfrio', 'ticker' => 'FRIO3'],
            ['name' => 'São Paulo Turismo', 'ticker' => 'AHEB3'],
            ['name' => 'São Paulo Turismo', 'ticker' => 'AHEB6'],
            ['name' => 'Bardella', 'ticker' => 'BDLL4'],
            ['name' => 'Celesc', 'ticker' => 'CLSC3'],
            ['name' => 'Cia. de Seg. Aliança da Bahia', 'ticker' => 'CSAB4'],
            ['name' => 'Panatlântica', 'ticker' => 'PATI4'],
            ['name' => 'Energisa MT', 'ticker' => 'ENMT4'],
            ['name' => 'Braskem', 'ticker' => 'BRKM6'],
            ['name' => 'Rio Paranapanema Energia', 'ticker' => 'GEPA3'],
            ['name' => 'Comgás', 'ticker' => 'CGAS3'],
            ['name' => 'Banco Mercantil do Brasil', 'ticker' => 'BMEB3'],
            ['name' => 'General Shopping & Outlets', 'ticker' => 'GSHP3'],
            ['name' => 'PINE', 'ticker' => 'PINE3'],
            ['name' => 'MRS Logística', 'ticker' => 'MRSA3B'],
            ['name' => 'MRS Logística', 'ticker' => 'MRSA5B'],
            ['name' => 'MRS Logística', 'ticker' => 'MRSA6B'],
            ['name' => 'FIEI3', 'ticker' => 'FIEI3'],
            ['name' => 'Adolpho Lindenberg', 'ticker' => 'CALI3'],
            ['name' => 'Estrela', 'ticker' => 'ESTR3'],
            ['name' => 'WLM', 'ticker' => 'WLMM3'],
            ['name' => 'Via', 'ticker' => 'VIIA3'],
            ['name' => 'Alfa Holdings', 'ticker' => 'RPAD6'],
            ['name' => 'Tronox Pigmentos', 'ticker' => 'CRPG3'],
            ['name' => 'Monteiro Aranha', 'ticker' => 'MOAR3'],
            ['name' => 'Consórcio Alfa', 'ticker' => 'BRGE8'],
            ['name' => 'Alfa Holdings', 'ticker' => 'RPAD5'],
            ['name' => 'Dtcom', 'ticker' => 'DTCY3'],
            ['name' => 'Elektro', 'ticker' => 'EKTR3'],
            ['name' => 'Bardella', 'ticker' => 'BDLL3'],
            ['name' => 'Plascar', 'ticker' => 'PLAS3'],
            ['name' => 'Banco Mercantil de Investimentos', 'ticker' => 'BMIN3'],
            ['name' => 'Nordon', 'ticker' => 'NORD3'],
            ['name' => 'Sondotécnica', 'ticker' => 'SOND6'],
            ['name' => 'COELBA', 'ticker' => 'CEEB5'],
            ['name' => 'Cia. de Seg. Aliança da Bahia', 'ticker' => 'CSAB3'],
            ['name' => 'Trevisa', 'ticker' => 'LUXM4'],
            ['name' => 'Consórcio Alfa', 'ticker' => 'BRGE7'],
            ['name' => 'Wetzel', 'ticker' => 'MWET3'],
            ['name' => 'Usiminas', 'ticker' => 'USIM6'],
            ['name' => 'São Paulo Turismo', 'ticker' => 'AHEB5'],
            ['name' => 'EDP Brasil', 'ticker' => 'ENBR3'],
            ['name' => 'METISA', 'ticker' => 'MTSA3'],
            ['name' => 'Eletrobras', 'ticker' => 'ELET5'],
            ['name' => 'Equatorial Energia Pará', 'ticker' => 'EQPA7'],
            ['name' => 'Boa Vista', 'ticker' => 'BOAS3'],
            ['name' => 'Cemepe', 'ticker' => 'MAPT4'],
            ['name' => 'COSERN', 'ticker' => 'CSRN6'],
            ['name' => 'Participações Aliança da Bahia', 'ticker' => 'PEAB4'],
            ['name' => 'COSERN', 'ticker' => 'CSRN5'],
            ['name' => 'Coelce', 'ticker' => 'COCE3'],
            ['name' => 'Ampla Energia', 'ticker' => 'CBEE3'],
            ['name' => 'Josapar', 'ticker' => 'JOPA4'],
            ['name' => 'CELGPAR', 'ticker' => 'GPAR3'],
            ['name' => 'Banco Modal', 'ticker' => 'MODL3'],
            ['name' => 'Karsten', 'ticker' => 'CTKA3'],
            ['name' => 'Mercantil do Brasil Financeira', 'ticker' => 'MERC3'],
            ['name' => 'DMFN3', 'ticker' => 'DMFN3'],
            ['name' => 'Naturgy (CEG)', 'ticker' => 'CEGR3'],
            ['name' => 'Cemepe', 'ticker' => 'MAPT3'],
            ['name' => 'CR2', 'ticker' => 'CRDE3'],
            ['name' => 'IGB Eletrônica', 'ticker' => 'IGBR3'],
            ['name' => 'Melhoramentos', 'ticker' => 'MSPA4'],
            ['name' => 'Conservas Oderich', 'ticker' => 'ODER4'],
            ['name' => 'Hermes Pardini', 'ticker' => 'PARD3'],
            ['name' => 'CASAN', 'ticker' => 'CASN3'],
            ['name' => 'WIZS3', 'ticker' => 'WIZS3'],
            ['name' => 'LLIS3', 'ticker' => 'LLIS3'],
            ['name' => 'Melhoramentos', 'ticker' => 'MSPA3'],
            ['name' => 'BRMalls', 'ticker' => 'BRML3'],
            ['name' => 'Dommo Energia', 'ticker' => 'DMMO3'],
            ['name' => 'Getnet', 'ticker' => 'GETT3'],
            ['name' => 'Getnet', 'ticker' => 'GETT4'],
            ['name' => 'SulAmérica', 'ticker' => 'SULA4'],
            ['name' => 'SulAmérica', 'ticker' => 'SULA3'],
            ['name' => 'CELPE', 'ticker' => 'CEPE5'],
            ['name' => 'Tecnosolo', 'ticker' => 'TCNO4'],
            ['name' => 'Tecnosolo', 'ticker' => 'TCNO3'],
            ['name' => 'CELPE', 'ticker' => 'CEPE6'],
            ['name' => 'Banco Inter', 'ticker' => 'BIDI4'],
            ['name' => 'Banco Inter', 'ticker' => 'BIDI3'],
            ['name' => 'CEEE GT', 'ticker' => 'EEEL4'],
            ['name' => 'CEEE GT', 'ticker' => 'EEEL3'],
            ['name' => 'BBRK3', 'ticker' => 'BBRK3'],
            ['name' => 'Sondotécnica', 'ticker' => 'SOND3'],
            ['name' => 'CESP', 'ticker' => 'CESP6'],
            ['name' => 'CESP', 'ticker' => 'CESP3'],
            ['name' => 'CESP', 'ticker' => 'CESP5'],
            ['name' => 'Encorpar', 'ticker' => 'ECPR4'],
            ['name' => 'Mosaico', 'ticker' => 'MOSI3'],
            ['name' => 'Focus Energia', 'ticker' => 'POWE3'],
            ['name' => 'Encorpar', 'ticker' => 'ECPR3'],
            ['name' => 'NotreDame Intermédica', 'ticker' => 'GNDI3'],
            ['name' => 'Lojas Americanas', 'ticker' => 'LAME4'],
            ['name' => 'Lojas Americanas', 'ticker' => 'LAME3'],
            ['name' => 'Omega Geração', 'ticker' => 'OMGE3'],
            ['name' => 'IGTA3', 'ticker' => 'IGTA3'],
            ['name' => 'JPSA3', 'ticker' => 'JPSA3'],
            ['name' => 'BRDT3', 'ticker' => 'BRDT3'],
            ['name' => 'JBDU4', 'ticker' => 'JBDU4'],
            ['name' => 'JBDU3', 'ticker' => 'JBDU3'],
            ['name' => 'Hering', 'ticker' => 'HGTX3'],
            ['name' => 'CCPR3', 'ticker' => 'CCPR3'],
            ['name' => 'DTEX3', 'ticker' => 'DTEX3'],
            ['name' => 'VVAR3', 'ticker' => 'VVAR3'],
            ['name' => 'Dimed', 'ticker' => 'PNVL4'],
            ['name' => 'Terra Santa', 'ticker' => 'TESA3'],
            ['name' => 'BTOW3', 'ticker' => 'BTOW3'],
            ['name' => 'Linx', 'ticker' => 'LINX3'],
            ['name' => 'Embpar', 'ticker' => 'BTTL3'],
            ['name' => 'GPCP3', 'ticker' => 'GPCP3'],
            ['name' => 'GPCP4', 'ticker' => 'GPCP4'],
            ['name' => 'Smiles', 'ticker' => 'SMLS3'],
            ['name' => 'MMX Mineração', 'ticker' => 'MMXM3'],
            ['name' => 'Biosev', 'ticker' => 'BSEV3'],
            ['name' => 'CNTO3', 'ticker' => 'CNTO3'],
            ['name' => 'AES Tietê Energia', 'ticker' => 'TIET4'],
            ['name' => 'AES Tietê Energia', 'ticker' => 'TIET3'],
            ['name' => 'Corrêa Ribeiro', 'ticker' => 'CORR4'],
            ['name' => 'CELPE', 'ticker' => 'CEPE3'],
            ['name' => 'Adolpho Lindenberg', 'ticker' => 'CALI4'],
            ['name' => 'Sansuy', 'ticker' => 'SNSY6'],
            ['name' => 'CASAN', 'ticker' => 'CASN4'],
            ['name' => 'EMAE', 'ticker' => 'EMAE3'],
            ['name' => 'Banpará', 'ticker' => 'BPAR3'],
            ['name' => 'Aliperti', 'ticker' => 'APTI4'],
            ['name' => 'FCA', 'ticker' => 'VSPT3'],
            ['name' => 'Metalgráfica Iguaçu', 'ticker' => 'MTIG3'],
            ['name' => 'Investimentos Bemge', 'ticker' => 'FIGE4'],
            ['name' => 'Trevisa', 'ticker' => 'LUXM3'],
            ['name' => 'Tekno', 'ticker' => 'TKNO3'],
            ['name' => 'Coelce', 'ticker' => 'COCE6'],
            ['name' => 'Mangels', 'ticker' => 'MGEL3'],
            ['name' => 'Santanense', 'ticker' => 'CTSA8'],
            ['name' => 'Minasmáquinas', 'ticker' => 'MMAQ4']
        ];
    }
}
