<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Repositories\AssetClassRepository;
use App\Repositories\AssetRepository;

class CryptocurrencySeeder extends Seeder
{
    protected $assetClassRepository;
    protected $assetRepository;

    public function __construct(AssetClassRepository $assetClassRepository, AssetRepository $assetRepository)
    {
        $this->assetClassRepository = $assetClassRepository;
        $this->assetRepository = $assetRepository;
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $assetClass = $this->assetClassRepository->getBySlug('cryptocurrencies');

        foreach ($this->getData() as $data) {
            $asset = $this->assetRepository->getAssetByTicker($data['ticker']);

            if ($asset) {
                continue;
            }

            $this->assetRepository->createAsset([
                'asset_class_id' => $assetClass->id,
                'ticker' => $data['ticker']
            ]);
        }
    }

    public function getData(): array
    {
        return [
            ['name' => '42 Coin', 'ticker' => '42'],
            ['name' => '365Coin', 'ticker' => '365'],
            ['name' => '404Coin', 'ticker' => '404'],
            ['name' => 'SixEleven', 'ticker' => '611'],
            ['name' => '808', 'ticker' => '808'],
            ['name' => 'EliteCoin', 'ticker' => '1337'],
            ['name' => '2015 coin', 'ticker' => '2015'],
            ['name' => 'Bitcoin', 'ticker' => 'BTC'],
            ['name' => 'Ethereum', 'ticker' => 'ETH'],
            ['name' => 'Litecoin', 'ticker' => 'LTC'],
            ['name' => 'Dash', 'ticker' => 'DASH'],
            ['name' => 'Monero', 'ticker' => 'XMR'],
            ['name' => 'Ethereum Classic', 'ticker' => 'ETC'],
            ['name' => 'ZCash', 'ticker' => 'ZEC'],
            ['name' => 'Bitshares', 'ticker' => 'BTS'],
            ['name' => 'DigiByte', 'ticker' => 'DGB'],
            ['name' => 'BitcoinDark', 'ticker' => 'BTCD'],
            ['name' => 'CraigsCoin', 'ticker' => 'CRAIG'],
            ['name' => 'Bitstake', 'ticker' => 'XBS'],
            ['name' => 'PayCoin', 'ticker' => 'XPY'],
            ['name' => 'ProsperCoin', 'ticker' => 'PRC'],
            ['name' => 'YbCoin', 'ticker' => 'YBC'],
            ['name' => 'DarkKush', 'ticker' => 'DANK'],
            ['name' => 'GiveCoin', 'ticker' => 'GIVE'],
            ['name' => 'KoboCoin', 'ticker' => 'KOBO'],
            ['name' => 'DarkToken', 'ticker' => 'DT'],
            ['name' => 'CETUS Coin', 'ticker' => 'CETI'],
            ['name' => 'Spreadcoin', 'ticker' => 'SPR'],
            ['name' => 'Insanity Coin', 'ticker' => 'WOLF'],
            ['name' => 'ACoin', 'ticker' => 'ACOIN'],
            ['name' => 'Aero Coin', 'ticker' => 'AERO'],
            ['name' => 'AlphaCoin', 'ticker' => 'ALF'],
            ['name' => 'Aegis', 'ticker' => 'AGS'],
            ['name' => 'AmericanCoin', 'ticker' => 'AMC'],
            ['name' => 'AlienCoin', 'ticker' => 'ALN'],
            ['name' => 'ApexCoin', 'ticker' => 'APEX'],
            ['name' => 'ArchCoin', 'ticker' => 'ARCH'],
            ['name' => 'Argentum', 'ticker' => 'ARG'],
            ['name' => 'AriCoin', 'ticker' => 'ARI'],
            ['name' => 'Aurora Coin', 'ticker' => 'AUR'],
            ['name' => 'BetaCoin', 'ticker' => 'BET'],
            ['name' => 'BeanCash', 'ticker' => 'BEAN'],
            ['name' => 'BlueCoin', 'ticker' => 'BLU'],
            ['name' => 'BQCoin', 'ticker' => 'BQC'],
            ['name' => 'MyriadCoin', 'ticker' => 'XMY'],
            ['name' => 'MoonCoin', 'ticker' => 'MOON'],
            ['name' => 'ZetaCoin', 'ticker' => 'ZET'],
            ['name' => 'SexCoin', 'ticker' => 'SXC'],
            ['name' => 'Quatloo', 'ticker' => 'QTL'],
            ['name' => 'EnergyCoin', 'ticker' => 'ENRG'],
            ['name' => 'QuarkCoin', 'ticker' => 'QRK'],
            ['name' => 'Riecoin', 'ticker' => 'RIC'],
            ['name' => 'Digitalcoin', 'ticker' => 'DGC'],
            ['name' => 'LimeCoinX', 'ticker' => 'LIMX'],
            ['name' => 'BitBar', 'ticker' => 'BTB'],
            ['name' => 'CAIx', 'ticker' => 'CAIX'],
            ['name' => 'BitMark', 'ticker' => 'BTMK'],
            ['name' => 'CryptoBuk', 'ticker' => 'BUK'],
            ['name' => 'Cachecoin', 'ticker' => 'CACH'],
            ['name' => 'BottleCaps', 'ticker' => 'CAP'],
            ['name' => 'CashCoin', 'ticker' => 'CASH'],
            ['name' => 'Catcoin', 'ticker' => 'CAT'],
            ['name' => 'CryptoBullion', 'ticker' => 'CBX'],
            ['name' => 'CannaCoin', 'ticker' => 'CCN'],
            ['name' => 'CinderCoin', 'ticker' => 'CIN'],
            ['name' => 'CINNICOIN', 'ticker' => 'CINNI'],
            ['name' => 'CopperLark', 'ticker' => 'CLR'],
            ['name' => 'CosmosCoin', 'ticker' => 'CMC'],
            ['name' => 'ChinaCoin', 'ticker' => 'CNC'],
            ['name' => 'ConcealCoin', 'ticker' => 'CNL'],
            ['name' => 'Community Coin', 'ticker' => 'COMM'],
            ['name' => 'CoolCoin', 'ticker' => 'COOL'],
            ['name' => 'CrackCoin', 'ticker' => 'CRACK'],
            ['name' => 'CryptCoin', 'ticker' => 'CRYPT'],
            ['name' => 'CasinoCoin', 'ticker' => 'CSC'],
            ['name' => 'eMark', 'ticker' => 'DEM'],
            ['name' => 'Diamond', 'ticker' => 'DMD'],
            ['name' => 'Verge', 'ticker' => 'XVG'],
            ['name' => 'DarkCash', 'ticker' => 'DRKC'],
            ['name' => 'DarkShibe', 'ticker' => 'DSB'],
            ['name' => 'DevCoin', 'ticker' => 'DVC'],
            ['name' => 'EarthCoin', 'ticker' => 'EAC'],
            ['name' => 'E-Gulden', 'ticker' => 'EFL'],
            ['name' => 'Elacoin', 'ticker' => 'ELC'],
            ['name' => 'Einsteinium', 'ticker' => 'EMC2'],
            ['name' => 'Emerald', 'ticker' => 'EMD'],
            ['name' => 'Exclusive Coin', 'ticker' => 'EXCL'],
            ['name' => 'ExeCoin', 'ticker' => 'EXE'],
            ['name' => 'EZCoin', 'ticker' => 'EZC'],
            ['name' => 'Flappy Coin', 'ticker' => 'FLAP'],
            ['name' => 'Fuel2Coin', 'ticker' => 'FC2'],
            ['name' => 'FireflyCoin', 'ticker' => 'FFC'],
            ['name' => 'FIBRE', 'ticker' => 'FIBRE'],
            ['name' => 'FireRoosterCoin', 'ticker' => 'FRC'],
            ['name' => 'FlutterCoin', 'ticker' => 'FLT'],
            ['name' => 'Franko', 'ticker' => 'FRK'],
            ['name' => 'FractalCoin', 'ticker' => 'FRAC'],
            ['name' => 'FastCoin', 'ticker' => 'FSTC'],
            ['name' => 'FeatherCoin', 'ticker' => 'FTC'],
            ['name' => 'GrandCoin', 'ticker' => 'GDC'],
            ['name' => 'GlobalCoin', 'ticker' => 'GLC'],
            ['name' => 'GoldCoin', 'ticker' => 'GLD'],
            ['name' => 'GalaxyCoin', 'ticker' => 'GLX'],
            ['name' => 'GlyphCoin', 'ticker' => 'GLYPH'],
            ['name' => 'GameLeagueCoin', 'ticker' => 'GML'],
            ['name' => 'GuerillaCoin', 'ticker' => 'GUE'],
            ['name' => 'Halcyon', 'ticker' => 'HAL'],
            ['name' => 'HoboNickels', 'ticker' => 'HBN'],
            ['name' => 'HunterCoin', 'ticker' => 'HUC'],
            ['name' => 'HeavyCoin', 'ticker' => 'HVC'],
            ['name' => 'HyperStake', 'ticker' => 'HYP'],
            ['name' => 'IceBergCoin', 'ticker' => 'ICB'],
            ['name' => 'Infinite Coin', 'ticker' => 'IFC'],
            ['name' => 'IOCoin', 'ticker' => 'IOC'],
            ['name' => 'IXcoin', 'ticker' => 'IXC'],
            ['name' => 'JumBucks Coin', 'ticker' => 'JBS'],
            ['name' => 'JunkCoin', 'ticker' => 'JKC'],
            ['name' => 'JudgeCoin', 'ticker' => 'JUDGE'],
            ['name' => 'Klondike Coin', 'ticker' => 'KDC'],
            ['name' => 'KeyCoin', 'ticker' => 'KEYC'],
            ['name' => 'KrugerCoin', 'ticker' => 'KGC'],
            ['name' => 'Lucky7Coin', 'ticker' => 'LK7'],
            ['name' => 'LuckyCoin', 'ticker' => 'LKY'],
            ['name' => 'LightSpeedCoin', 'ticker' => 'LSD'],
            ['name' => 'Litebar', 'ticker' => 'LTB'],
            ['name' => 'LitecoinDark', 'ticker' => 'LTCD'],
            ['name' => 'LitecoinX', 'ticker' => 'LTCX'],
            ['name' => 'LibrexCoin', 'ticker' => 'LXC'],
            ['name' => 'LycanCoin', 'ticker' => 'LYC'],
            ['name' => 'MaxCoin', 'ticker' => 'MAX'],
            ['name' => 'MegaCoin', 'ticker' => 'MEC'],
            ['name' => 'MediterraneanCoin', 'ticker' => 'MED'],
            ['name' => 'Minerals Coin', 'ticker' => 'MINRL'],
            ['name' => 'MintCoin', 'ticker' => 'MINT'],
            ['name' => 'Cryptsy Mining Contract', 'ticker' => 'MN'],
            ['name' => 'MinCoin', 'ticker' => 'MINC'],
            ['name' => 'MurrayCoin', 'ticker' => 'MRY'],
            ['name' => 'MazaCoin', 'ticker' => 'MZC'],
            ['name' => 'NanoToken', 'ticker' => 'NAN'],
            ['name' => 'Nautilus Coin', 'ticker' => 'NAUT'],
            ['name' => 'NavCoin', 'ticker' => 'NAV'],
            ['name' => 'Nybble', 'ticker' => 'NBL'],
            ['name' => 'NoirBits', 'ticker' => 'NRB'],
            ['name' => 'NobleCoin', 'ticker' => 'NOBL'],
            ['name' => 'NoirShares', 'ticker' => 'NRS'],
            ['name' => 'Namecoin', 'ticker' => 'NMC'],
            ['name' => 'NyanCoin', 'ticker' => 'NYAN'],
            ['name' => 'OpalCoin', 'ticker' => 'OPAL'],
            ['name' => 'Orbitcoin', 'ticker' => 'ORB'],
            ['name' => 'PhilosophersStone', 'ticker' => 'PHS'],
            ['name' => 'PotCoin', 'ticker' => 'POT'],
            ['name' => 'PseudoCash', 'ticker' => 'PSEUD'],
            ['name' => 'PhoenixCoin', 'ticker' => 'PXC'],
            ['name' => 'PayCoin', 'ticker' => 'PYC'],
            ['name' => 'Reddcoin', 'ticker' => 'RDD'],
            ['name' => 'RipOffCoin', 'ticker' => 'RIPO'],
            ['name' => 'RonPaulCoin', 'ticker' => 'RPC'],
            ['name' => 'RotoCoin', 'ticker' => 'RT2'],
            ['name' => 'RoyalCoin', 'ticker' => 'RYC'],
            ['name' => 'RazorCoin', 'ticker' => 'RZR'],
            ['name' => 'Saturn2Coin', 'ticker' => 'SAT2'],
            ['name' => 'StableCoin', 'ticker' => 'SBC'],
            ['name' => 'SaffronCoin', 'ticker' => 'SFR'],
            ['name' => 'ShadeCoin', 'ticker' => 'SHADE'],
            ['name' => 'ShieldCoin', 'ticker' => 'SHLD'],
            ['name' => 'SilkCoin', 'ticker' => 'SILK'],
            ['name' => 'SterlingCoin', 'ticker' => 'SLG'],
            ['name' => 'SmartCoin', 'ticker' => 'SMC'],
            ['name' => 'SoleCoin', 'ticker' => 'SOLE'],
            ['name' => 'SpainCoin', 'ticker' => 'SPA'],
            ['name' => 'Spots', 'ticker' => 'SPOTS'],
            ['name' => 'SecureCoin', 'ticker' => 'SRC'],
            ['name' => 'SSVCoin', 'ticker' => 'SSV'],
            ['name' => 'SuperCoin', 'ticker' => 'SUPER'],
            ['name' => 'SyncCoin', 'ticker' => 'SYNC'],
            ['name' => 'SysCoin', 'ticker' => 'SYS'],
            ['name' => 'TagCoin', 'ticker' => 'TAG'],
            ['name' => 'TakCoin', 'ticker' => 'TAK'],
            ['name' => 'TeslaCoin', 'ticker' => 'TES'],
            ['name' => 'TigerCoin', 'ticker' => 'TGC'],
            ['name' => 'TittieCoin', 'ticker' => 'TIT'],
            ['name' => 'TorCoin', 'ticker' => 'TOR'],
            ['name' => 'TerraCoin', 'ticker' => 'TRC'],
            ['name' => 'TitCoin', 'ticker' => 'TITC'],
            ['name' => 'Umbrella', 'ticker' => 'ULTC'],
            ['name' => 'UnbreakableCoin', 'ticker' => 'UNB'],
            ['name' => 'Unobtanium', 'ticker' => 'UNO'],
            ['name' => 'UroCoin', 'ticker' => 'URO'],
            ['name' => 'UnitaryStatus Dollar', 'ticker' => 'USDE'],
            ['name' => 'UltraCoin', 'ticker' => 'UTC'],
            ['name' => 'Utility Coin', 'ticker' => 'UTIL'],
            ['name' => 'VidioCoin', 'ticker' => 'VDO'],
            ['name' => 'ViaCoin', 'ticker' => 'VIA'],
            ['name' => 'VootCoin', 'ticker' => 'VOOT'],
            ['name' => 'VeriCoin', 'ticker' => 'VRC'],
            ['name' => 'Vertcoin', 'ticker' => 'VTC'],
            ['name' => 'WorldCoin', 'ticker' => 'WDC'],
            ['name' => 'SapienceCoin', 'ticker' => 'XAI'],
            ['name' => 'SocialXbotCoin', 'ticker' => 'XBOT'],
            ['name' => 'X11 Coin', 'ticker' => 'XC'],
            ['name' => 'Xcash', 'ticker' => 'XCSH'],
            ['name' => 'Crypti', 'ticker' => 'XCR'],
            ['name' => 'JouleCoin', 'ticker' => 'XJO'],
            ['name' => 'LibertyCoin', 'ticker' => 'XLB'],
            ['name' => 'StealthCoin', 'ticker' => 'XST'],
            ['name' => 'XXXCoin', 'ticker' => 'XXX'],
            ['name' => 'YAcCoin', 'ticker' => 'YAC'],
            ['name' => 'ZCC Coin', 'ticker' => 'ZCC'],
            ['name' => 'ZedCoins', 'ticker' => 'ZED'],
            ['name' => 'ByteCoin', 'ticker' => 'BCN'],
            ['name' => 'Elektron', 'ticker' => 'EKN'],
            ['name' => 'DigitalNote', 'ticker' => 'XDN'],
            ['name' => 'XauCoin', 'ticker' => 'XAU'],
            ['name' => 'BurstCoin', 'ticker' => 'BURST'],
            ['name' => 'StorjCoin', 'ticker' => 'SJCX'],
            ['name' => 'BigCoin', 'ticker' => 'HUGE'],
            ['name' => '007 coin', 'ticker' => '7'],
            ['name' => 'MonaCoin', 'ticker' => 'MONA'],
            ['name' => 'TekCoin', 'ticker' => 'TEK'],
            ['name' => 'Neutron', 'ticker' => 'NTRN'],
            ['name' => 'Sling Coin', 'ticker' => 'SLING'],
            ['name' => 'Stability Shares', 'ticker' => 'XSI'],
            ['name' => 'KryptCoin', 'ticker' => 'KTK'],
            ['name' => 'FairCoin', 'ticker' => 'FAIR'],
            ['name' => 'Gulden', 'ticker' => 'NLG'],
            ['name' => 'RubyCoin', 'ticker' => 'RBY'],
            ['name' => 'PesetaCoin', 'ticker' => 'PTC'],
            ['name' => 'Kore', 'ticker' => 'KORE'],
            ['name' => 'Wild Beast Coin', 'ticker' => 'WBB'],
            ['name' => 'Sonic Screw Driver Coin', 'ticker' => 'SSD'],
            ['name' => 'Dnotes', 'ticker' => 'NOTE'],
            ['name' => 'Flo', 'ticker' => 'FLO'],
            ['name' => 'MaieutiCoin', 'ticker' => 'MMXIV'],
            ['name' => '8BIT Coin', 'ticker' => '8BIT'],
            ['name' => 'Sativa Coin', 'ticker' => 'STV'],
            ['name' => 'AeroMe', 'ticker' => 'AM'],
            ['name' => 'NakomotoDark', 'ticker' => 'NKT'],
            ['name' => 'GhostCoin', 'ticker' => 'GHC'],
            ['name' => 'ArtByte', 'ticker' => 'ABY'],
            ['name' => 'MasterTraderCoin', 'ticker' => 'MTR'],
            ['name' => 'BitCredit', 'ticker' => 'BCR'],
            ['name' => 'Pebble Coin', 'ticker' => 'XPB'],
            ['name' => 'Dirac Coin', 'ticker' => 'XDQ'],
            ['name' => 'Folding Coin', 'ticker' => 'FLDC'],
            ['name' => 'Social Media Coin', 'ticker' => 'SMAC'],
            ['name' => 'Ucoin', 'ticker' => 'U'],
            ['name' => 'Unitus', 'ticker' => 'UIS'],
            ['name' => 'CypherPunkCoin', 'ticker' => 'CYP'],
            ['name' => 'QuBuck Coin', 'ticker' => 'QBK'],
            ['name' => 'MaryJane Coin', 'ticker' => 'MARYJ'],
            ['name' => 'OmniCron', 'ticker' => 'OMC'],
            ['name' => 'GigCoin', 'ticker' => 'GIG'],
            ['name' => 'CyberCoin', 'ticker' => 'CC'],
            ['name' => 'Vtorrent', 'ticker' => 'VTR'],
            ['name' => 'MetalCoin', 'ticker' => 'METAL'],
            ['name' => 'GreenCoin', 'ticker' => 'GRE'],
            ['name' => 'XG Sports', 'ticker' => 'XG'],
            ['name' => 'ChildCoin', 'ticker' => 'CHILD'],
            ['name' => 'Instamine Nuggets', 'ticker' => 'MINE'],
            ['name' => 'ROS Coin', 'ticker' => 'ROS'],
            ['name' => 'Unattanium', 'ticker' => 'UNAT'],
            ['name' => 'GAIA Platform', 'ticker' => 'GAIA'],
            ['name' => 'Cryptonite', 'ticker' => 'XCN'],
            ['name' => 'Gridmaster', 'ticker' => 'GMC'],
            ['name' => 'MemoryCoin', 'ticker' => 'MMC'],
            ['name' => 'ConSpiracy Coin', 'ticker' => 'CYC'],
            ['name' => 'MasterCoin', 'ticker' => 'MSC'],
            ['name' => 'EggCoin', 'ticker' => 'EGG'],
            ['name' => 'Camcoin', 'ticker' => 'CAMC'],
            ['name' => 'Ribbit Rewards', 'ticker' => 'RBR'],
            ['name' => 'ICASH', 'ticker' => 'ICASH'],
            ['name' => 'Node', 'ticker' => 'NODE'],
            ['name' => 'SoonCoin', 'ticker' => 'SOON'],
            ['name' => 'BitMiles', 'ticker' => 'BTMI'],
            ['name' => 'Event Token', 'ticker' => 'EVENT'],
            ['name' => '1Credit', 'ticker' => '1CR'],
            ['name' => 'ViorCoin', 'ticker' => 'VIOR'],
            ['name' => 'VirtualMining Coin', 'ticker' => 'VMC'],
            ['name' => 'MarsCoin', 'ticker' => 'MARSC'],
            ['name' => 'Equilibrium Coin', 'ticker' => 'EQM'],
            ['name' => 'IslaCoin', 'ticker' => 'ISL'],
            ['name' => 'Quicksilver coin', 'ticker' => 'QSLV'],
            ['name' => 'DeOxyRibose', 'ticker' => 'XNA'],
            ['name' => 'SkullBuzz', 'ticker' => 'SKB'],
            ['name' => 'CryptoFocus', 'ticker' => 'FCS'],
            ['name' => 'Nexus', 'ticker' => 'NXS'],
            ['name' => 'EagsCoin', 'ticker' => 'EAGS'],
            ['name' => 'MultiWallet Coin', 'ticker' => 'MWC'],
            ['name' => 'MarsCoin', 'ticker' => 'MARS'],
            ['name' => 'Megastake', 'ticker' => 'XMS'],
            ['name' => 'Singular', 'ticker' => 'SIGU'],
            ['name' => 'SupplyShock', 'ticker' => 'M1'],
            ['name' => 'DarkBit', 'ticker' => 'DB'],
            ['name' => 'Crypto', 'ticker' => 'CTO'],
            ['name' => 'BitLux', 'ticker' => 'BITL'],
            ['name' => 'FutCoin', 'ticker' => 'FUTC'],
            ['name' => 'TamaGucci', 'ticker' => 'TAM'],
            ['name' => 'MorpheusCoin', 'ticker' => 'MRP'],
            ['name' => 'Forever Coin', 'ticker' => 'XFC'],
            ['name' => 'BananaBits', 'ticker' => 'NANAS'],
            ['name' => 'Anarchists Prime', 'ticker' => 'ACP'],
            ['name' => 'Droidz', 'ticker' => 'DRZ'],
            ['name' => 'BowsCoin', 'ticker' => 'BSC'],
            ['name' => 'DarkTron', 'ticker' => 'DRKT'],
            ['name' => 'CryptoCircuits', 'ticker' => 'CIRC'],
            ['name' => 'Empyrean', 'ticker' => 'EPY'],
            ['name' => 'Squall Coin', 'ticker' => 'SQL'],
            ['name' => 'Charity Coin', 'ticker' => 'CHA'],
            ['name' => 'Milllionaire Coin', 'ticker' => 'MIL'],
            ['name' => 'Number7', 'ticker' => 'N7'],
            ['name' => 'Cygnus', 'ticker' => 'CYG'],
            ['name' => 'LGBTQoin', 'ticker' => 'LGBTQ'],
            ['name' => 'Uther', 'ticker' => 'UTH'],
            ['name' => 'MediumProject', 'ticker' => 'MPRO'],
            ['name' => 'KATZcoin', 'ticker' => 'KATZ'],
            ['name' => 'Supreme', 'ticker' => 'SPM'],
            ['name' => 'Flash', 'ticker' => 'FLX'],
            ['name' => 'BolivarCoin', 'ticker' => 'BOLI'],
            ['name' => 'CludCoin', 'ticker' => 'CLUD'],
            ['name' => 'High Voltage Coin', 'ticker' => 'HVCO'],
            ['name' => 'GIZMOcoin', 'ticker' => 'GIZ'],
            ['name' => 'Fuzzballs', 'ticker' => 'FUZZ'],
            ['name' => 'SecretCoin', 'ticker' => 'SCRT'],
            ['name' => 'Ratecoin', 'ticker' => 'XRA'],
            ['name' => 'Digital Bullion Gold', 'ticker' => 'DBG'],
            ['name' => 'WMCoin', 'ticker' => 'WMC'],
            ['name' => 'GothicCoin', 'ticker' => 'GOTX'],
            ['name' => 'ShrekCoin', 'ticker' => 'SHREK'],
            ['name' => 'Revenu', 'ticker' => 'REV'],
            ['name' => 'PabyosiCoin', 'ticker' => 'PBC'],
            ['name' => 'Obscurebay', 'ticker' => 'OBS'],
            ['name' => 'ExitCoin', 'ticker' => 'EXIT'],
            ['name' => 'EducoinV', 'ticker' => 'EDUC'],
            ['name' => 'Clinton', 'ticker' => 'CLINT'],
            ['name' => 'Clockcoin', 'ticker' => 'CKC'],
            ['name' => 'VIP Tokens', 'ticker' => 'VIP'],
            ['name' => 'NXEcoin', 'ticker' => 'NXE'],
            ['name' => 'ZoomCoin', 'ticker' => 'ZOOM'],
            ['name' => 'YobitVirtualCoin', 'ticker' => 'YOVI'],
            ['name' => 'OrlyCoin', 'ticker' => 'ORLY'],
            ['name' => 'KubosCoin', 'ticker' => 'KUBOS'],
            ['name' => 'SharkCoin', 'ticker' => 'SAK'],
            ['name' => 'EvilCoin', 'ticker' => 'EVIL'],
            ['name' => 'CobraCoin', 'ticker' => 'COX'],
            ['name' => 'BitSend', 'ticker' => 'BSD'],
            ['name' => 'Destiny', 'ticker' => 'DES'],
            ['name' => '16BitCoin', 'ticker' => 'BIT16'],
            ['name' => 'CometCoin', 'ticker' => 'CMTC'],
            ['name' => 'ChessCoin', 'ticker' => 'CHESS'],
            ['name' => 'ReeCoin', 'ticker' => 'REE'],
            ['name' => 'Marvelous', 'ticker' => 'MARV'],
            ['name' => 'Omni', 'ticker' => 'OMNI'],
            ['name' => 'TrollTokens', 'ticker' => 'TRTK'],
            ['name' => 'Let it Ride', 'ticker' => 'LIR'],
            ['name' => 'ScryptCoin', 'ticker' => 'SCRPT'],
            ['name' => 'Specie', 'ticker' => 'SPCIE'],
            ['name' => 'CryptoJacks', 'ticker' => 'CJ'],
            ['name' => 'PutinCoin', 'ticker' => 'PUT'],
            ['name' => 'Kraken', 'ticker' => 'KRAK'],
            ['name' => 'iBankCoin', 'ticker' => 'IBANK'],
            ['name' => 'World Gold Coin', 'ticker' => 'WRLGC'],
            ['name' => 'BitMoon', 'ticker' => 'BM'],
            ['name' => 'Frankywillcoin', 'ticker' => 'FRWC'],
            ['name' => 'Psilocybin', 'ticker' => 'PSY'],
            ['name' => 'RustCoin', 'ticker' => 'RUST'],
            ['name' => 'NewZealandCoin', 'ticker' => 'NZC'],
            ['name' => 'PokeChain', 'ticker' => 'XPOKE'],
            ['name' => 'MudraCoin', 'ticker' => 'MUDRA'],
            ['name' => 'PizzaCoin', 'ticker' => 'PIZZA'],
            ['name' => 'Lutetium Coin', 'ticker' => 'LC'],
            ['name' => 'ExaByte (EXB)', 'ticker' => 'EXB'],
            ['name' => 'Komodo', 'ticker' => 'KMD'],
            ['name' => 'GoldBlocks', 'ticker' => 'GB'],
            ['name' => 'EDC Blockchain', 'ticker' => 'EDC'],
            ['name' => 'WayCoin', 'ticker' => 'WAY'],
            ['name' => 'MollyCoin', 'ticker' => 'TAB'],
            ['name' => 'Save The Ocean', 'ticker' => 'STO'],
            ['name' => 'CarterCoin', 'ticker' => 'CTC'],
            ['name' => 'MedicCoin', 'ticker' => 'MDC'],
            ['name' => 'FuturePoints', 'ticker' => 'FTP'],
            ['name' => 'Zeta2Coin', 'ticker' => 'ZYD'],
            ['name' => 'MustangCoin', 'ticker' => 'MST'],
            ['name' => 'Goonies', 'ticker' => 'GOON'],
            ['name' => 'ZoneCoin', 'ticker' => 'ZNE'],
            ['name' => 'Circuits of Value', 'ticker' => 'COVAL'],
            ['name' => 'DarkGold', 'ticker' => 'DGDC'],
            ['name' => 'TodayCoin', 'ticker' => 'TODAY'],
            ['name' => 'RootCoin', 'ticker' => 'ROOT'],
            ['name' => 'DopeCoin', 'ticker' => 'DOPE'],
            ['name' => 'FCoin', 'ticker' => 'FX'],
            ['name' => 'Pioneershares', 'ticker' => 'PIO'],
            ['name' => 'PROUD Money', 'ticker' => 'PROUD'],
            ['name' => 'Samsara Coin', 'ticker' => 'SMSR'],
            ['name' => 'Ubiqoin', 'ticker' => 'UBIQ'],
            ['name' => 'Armory Coin', 'ticker' => 'ARM'],
            ['name' => 'RingCoin', 'ticker' => 'RING'],
            ['name' => 'Lazarus', 'ticker' => 'LAZ'],
            ['name' => 'BitCurrency', 'ticker' => 'BTCR'],
            ['name' => 'FaucetCoin', 'ticker' => 'FCTC'],
            ['name' => 'Dark Moon', 'ticker' => 'MOOND'],
            ['name' => 'DollarCoin', 'ticker' => 'DLC'],
            ['name' => 'Swiscoin', 'ticker' => 'SCN'],
            ['name' => 'BitBronze', 'ticker' => 'BRONZ'],
            ['name' => 'Shilling', 'ticker' => 'SH'],
            ['name' => 'BuzzCoin', 'ticker' => 'BUZZ'],
            ['name' => 'Mind Gene', 'ticker' => 'MG'],
            ['name' => 'PSIcoin', 'ticker' => 'PSI'],
            ['name' => 'Opair', 'ticker' => 'XPO'],
            ['name' => 'PesoBit', 'ticker' => 'PSB'],
            ['name' => 'Fitcoin', 'ticker' => 'FIT'],
            ['name' => 'PantherCoin', 'ticker' => 'PINKX'],
            ['name' => 'Unfed Coin', 'ticker' => 'UNF'],
            ['name' => 'SportsCoin', 'ticker' => 'SPORT'],
            ['name' => 'NineElevenTruthCoin', 'ticker' => 'NTC'],
            ['name' => 'EGOcoin', 'ticker' => 'EGO'],
            ['name' => 'GBR Coin', 'ticker' => 'GBRC'],
            ['name' => 'Halloween Coin', 'ticker' => 'HALLO'],
            ['name' => 'BaseballCardCoin', 'ticker' => 'BBCC'],
            ['name' => 'EmiratesGoldCoin', 'ticker' => 'EMIGR'],
            ['name' => 'BighanCoin', 'ticker' => 'BHC'],
            ['name' => 'Craftcoin', 'ticker' => 'CRAFT'],
            ['name' => 'OlympCoin', 'ticker' => 'OLYMP'],
            ['name' => 'DelightPay', 'ticker' => 'DPAY'],
            ['name' => 'AntiLitecoin', 'ticker' => 'ANTC'],
            ['name' => 'JobsCoin', 'ticker' => 'JOBS'],
            ['name' => 'DogeGoreCoin', 'ticker' => 'DGORE'],
            ['name' => 'Resumeo Shares', 'ticker' => 'RMS'],
            ['name' => 'FujiCoin', 'ticker' => 'FJC'],
            ['name' => 'Vaporcoin', 'ticker' => 'VAPOR'],
            ['name' => 'ZCoin', 'ticker' => 'XZC'],
            ['name' => 'Premium', 'ticker' => 'PRE'],
            ['name' => 'CaliphCoin', 'ticker' => 'CALC'],
            ['name' => 'LeaCoin', 'ticker' => 'LEA'],
            ['name' => 'Californium', 'ticker' => 'CF'],
            ['name' => 'CoffeeCoin', 'ticker' => 'CFC'],
            ['name' => 'BlackShadowCoin', 'ticker' => 'BS'],
            ['name' => 'JiffyCoin', 'ticker' => 'JIF'],
            ['name' => 'Moneta', 'ticker' => 'MONETA'],
            ['name' => 'Rublebit', 'ticker' => 'RUBIT'],
            ['name' => 'HappyCreatorCoin', 'ticker' => 'HCC'],
            ['name' => 'BrainCoin', 'ticker' => 'BRAIN'],
            ['name' => 'RoyalCoin', 'ticker' => 'ROYAL'],
            ['name' => 'BigLifeCoin', 'ticker' => 'LFC'],
            ['name' => 'Zurcoin', 'ticker' => 'ZUR'],
            ['name' => 'PeaceCoin', 'ticker' => 'PEC'],
            ['name' => 'Goldmaxcoin', 'ticker' => 'GMX'],
            ['name' => '32Bitcoin', 'ticker' => '32BIT'],
            ['name' => 'GanjaCoin V2', 'ticker' => 'GNJ'],
            ['name' => 'TeamUP', 'ticker' => 'TEAM'],
            ['name' => 'ScryptToken', 'ticker' => 'SCT'],
            ['name' => 'LanaCoin', 'ticker' => 'LANA'],
            ['name' => 'Elementrem', 'ticker' => 'ELE'],
            ['name' => 'GuccioneCoin', 'ticker' => 'GCC'],
            ['name' => 'EqualCoin', 'ticker' => 'EQUAL'],
            ['name' => '2BACCO Coin', 'ticker' => '2BACCO'],
            ['name' => 'DarkKnightCoin', 'ticker' => 'DKC'],
            ['name' => 'Community Coin', 'ticker' => 'COC'],
            ['name' => 'ChoofCoin', 'ticker' => 'CHOOF'],
            ['name' => 'CashOut', 'ticker' => 'CSH'],
            ['name' => 'ZClassic', 'ticker' => 'ZCL'],
            ['name' => 'RoyalCoin 2.0', 'ticker' => 'RYCN'],
            ['name' => 'Pabyosi Coin', 'ticker' => 'PCS'],
            ['name' => 'NetBit', 'ticker' => 'NBIT'],
            ['name' => 'WineCoin', 'ticker' => 'WINE'],
            ['name' => 'ARK', 'ticker' => 'ARK'],
            ['name' => 'ZCashDarkCoin', 'ticker' => 'ZECD'],
            ['name' => 'WashingtonCoin', 'ticker' => 'WASH'],
            ['name' => 'LuckyBlocks', 'ticker' => 'LUCKY'],
            ['name' => 'InsaneCoin', 'ticker' => 'INSANE'],
            ['name' => 'LuckChain', 'ticker' => 'BASH'],
            ['name' => 'FameCoin', 'ticker' => 'FAME'],
            ['name' => 'LiviaCoin', 'ticker' => 'LIV'],
            ['name' => 'EtherDoge', 'ticker' => 'DOGETH'],
            ['name' => 'KiloCoin', 'ticker' => 'KLC'],
            ['name' => 'Hush', 'ticker' => 'HUSH'],
            ['name' => 'BitLuckCoin', 'ticker' => 'BTLC'],
            ['name' => 'Dream8Coin', 'ticker' => 'DRM8'],
            ['name' => 'Ebitz', 'ticker' => 'EBZ'],
            ['name' => 'Free Game Zone', 'ticker' => 'FGZ'],
            ['name' => 'BosonCoin', 'ticker' => 'BOSON'],
            ['name' => 'ArtexCoin', 'ticker' => 'ATX'],
            ['name' => 'PlatiniumCoin', 'ticker' => 'PNC'],
            ['name' => 'BeardDollars', 'ticker' => 'BRDD'],
            ['name' => 'BipCoin', 'ticker' => 'BIPC'],
            ['name' => 'XenCoin', 'ticker' => 'XNC'],
            ['name' => 'Enigma', 'ticker' => 'XNG'],
            ['name' => 'Cannabis Industry Coin', 'ticker' => 'XCI'],
            ['name' => 'LookCoin', 'ticker' => 'LOOK'],
            ['name' => 'MIScoin', 'ticker' => 'MIS'],
            ['name' => 'WorldPay', 'ticker' => 'WOP'],
            ['name' => 'ConquestCoin', 'ticker' => 'CQST'],
            ['name' => 'TheChiefCoin', 'ticker' => 'CHIEF'],
            ['name' => 'Russiacoin', 'ticker' => 'RC'],
            ['name' => 'PandaCoin', 'ticker' => 'PND'],
            ['name' => 'Canada eCoin', 'ticker' => 'ECAD'],
            ['name' => 'OptionCoin', 'ticker' => 'OPTION'],
            ['name' => 'Avatar Coin', 'ticker' => 'AV'],
            ['name' => 'Limited Coin', 'ticker' => 'LTD'],
            ['name' => 'GameUnits', 'ticker' => 'UNITS'],
            ['name' => 'GAKHcoin', 'ticker' => 'GAKH'],
            ['name' => 'S88 Coin', 'ticker' => 'S8C'],
            ['name' => 'Allsafe', 'ticker' => 'ASAFE2'],
            ['name' => 'LiteCreed', 'ticker' => 'LTCR'],
            ['name' => 'ProCoin', 'ticker' => 'XPRO'],
            ['name' => 'Astral', 'ticker' => 'ASTR'],
            ['name' => 'GiftNet', 'ticker' => 'GIFT'],
            ['name' => 'PureVidz', 'ticker' => 'VIDZ'],
            ['name' => 'Incrementum', 'ticker' => 'INC'],
            ['name' => 'PentaCoin', 'ticker' => 'PTA'],
            ['name' => 'AcidCoin', 'ticker' => 'ACID'],
            ['name' => 'ReturnCoin', 'ticker' => 'RNC'],
            ['name' => 'TwisterCoin', 'ticker' => 'TWIST'],
            ['name' => 'PayPeer', 'ticker' => 'PAYP'],
            ['name' => 'LeninCoin', 'ticker' => 'LENIN'],
            ['name' => 'MrsaCoin', 'ticker' => 'MRSA'],
            ['name' => 'OsmiumCoin', 'ticker' => 'OS76'],
            ['name' => 'Bikercoins', 'ticker' => 'BIC'],
            ['name' => 'CryptoPennies', 'ticker' => 'CRPS'],
            ['name' => 'NeptuneClassic', 'ticker' => 'NTCC'],
            ['name' => 'HexxCoin', 'ticker' => 'HXX'],
            ['name' => 'Ghost Coin', 'ticker' => 'SPKTR'],
            ['name' => 'MachineCoin', 'ticker' => 'MAC'],
            ['name' => 'SelenCoin', 'ticker' => 'SEL'],
            ['name' => 'Noocoin', 'ticker' => 'NOO'],
            ['name' => '23 Skidoo', 'ticker' => 'CHAO'],
            ['name' => 'GoldenBird', 'ticker' => 'XGB'],
            ['name' => 'YamahaCoin', 'ticker' => 'YMC'],
            ['name' => 'JokerCoin', 'ticker' => 'JOK'],
            ['name' => 'GravityBit', 'ticker' => 'GBIT'],
            ['name' => 'TeCoin', 'ticker' => 'TEC'],
            ['name' => 'BombCoin', 'ticker' => 'BOMBC'],
            ['name' => 'Ride My Car', 'ticker' => 'RIDE'],
            ['name' => 'Klingon Empire Darsek', 'ticker' => 'KED'],
            ['name' => 'Internet of People', 'ticker' => 'IOP'],
            ['name' => 'Elysium', 'ticker' => 'ELS'],
            ['name' => 'KushCoin', 'ticker' => 'KUSH'],
            ['name' => 'Eryllium', 'ticker' => 'ERY'],
            ['name' => 'Opes', 'ticker' => 'OPES'],
            ['name' => 'Ratio', 'ticker' => 'RATIO'],
            ['name' => 'SmurfCoin', 'ticker' => 'SMF'],
            ['name' => 'TechCoin', 'ticker' => 'TECH'],
            ['name' => 'CircuitCoin', 'ticker' => 'CIR'],
            ['name' => 'LePenCoin', 'ticker' => 'LEPEN'],
            ['name' => 'MarxCoin', 'ticker' => 'MARX'],
            ['name' => 'HazeCoin', 'ticker' => 'HAZE'],
            ['name' => 'Printerium', 'ticker' => 'PRX'],
            ['name' => 'PacCoin', 'ticker' => 'PAC'],
            ['name' => 'Impeach', 'ticker' => 'IMPCH'],
            ['name' => 'ErrorCoin', 'ticker' => 'ERR'],
            ['name' => 'TrueInvestmentCoin', 'ticker' => 'TIC'],
            ['name' => 'NukeCoin', 'ticker' => 'NUKE'],
            ['name' => 'Solarflarecoin', 'ticker' => 'SFC'],
            ['name' => 'JaneCoin', 'ticker' => 'JANE'],
            ['name' => 'ParanoiaCoin', 'ticker' => 'PARA'],
            ['name' => 'MasterMint', 'ticker' => 'MM'],
            ['name' => 'Citadel', 'ticker' => 'CTL'],
            ['name' => 'Zilbercoin', 'ticker' => 'ZBC'],
            ['name' => 'FirstCoin', 'ticker' => 'FRST'],
            ['name' => 'OroCoin', 'ticker' => 'ORO'],
            ['name' => 'Alexandrite', 'ticker' => 'ALEX'],
            ['name' => 'TrashBurn', 'ticker' => 'TBCX'],
            ['name' => 'MasterCar', 'ticker' => 'MCAR'],
            ['name' => 'TechShares', 'ticker' => 'THS'],
            ['name' => 'AcesCoin', 'ticker' => 'ACES'],
            ['name' => 'United Arab Emirates Coin', 'ticker' => 'UAEC'],
            ['name' => 'EagleCoin', 'ticker' => 'EA'],
            ['name' => 'CreativeChain', 'ticker' => 'CREA'],
            ['name' => 'BeaverCoin', 'ticker' => 'BVC'],
            ['name' => 'FindCoin', 'ticker' => 'FIND'],
            ['name' => 'MeLite', 'ticker' => 'MLITE'],
            ['name' => 'StalinCoin', 'ticker' => 'STALIN'],
            ['name' => 'TattooCoin', 'ticker' => 'TSE'],
            ['name' => 'VaultCoin', 'ticker' => 'VLTC'],
            ['name' => 'BioBar', 'ticker' => 'BIOB'],
            ['name' => 'Zero', 'ticker' => 'ZER'],
            ['name' => 'OpenChat', 'ticker' => 'CHAT'],
            ['name' => 'Canada eCoin', 'ticker' => 'CDN'],
            ['name' => 'Zoin', 'ticker' => 'ZOI'],
            ['name' => 'Honey', 'ticker' => 'HONEY'],
            ['name' => 'MartexCoin', 'ticker' => 'MXT'],
            ['name' => 'Musicoin', 'ticker' => 'MUSIC'],
            ['name' => 'BitVegan', 'ticker' => 'VEG'],
            ['name' => 'Mbitbooks', 'ticker' => 'MBIT'],
            ['name' => 'Zennies', 'ticker' => 'ZENI'],
            ['name' => 'PlanetCoin', 'ticker' => 'PLANET'],
            ['name' => 'DuckDuckCoin', 'ticker' => 'DUCK'],
            ['name' => 'BnrtxCoin', 'ticker' => 'BNX'],
            ['name' => 'RenosCoin', 'ticker' => 'RNS'],
            ['name' => 'DubaiCoin', 'ticker' => 'DBIX'],
            ['name' => 'VirtacoinPlus', 'ticker' => 'XVP'],
            ['name' => 'Doubloon', 'ticker' => 'BOAT'],
            ['name' => 'TajCoin', 'ticker' => 'TAJ'],
            ['name' => 'Impact', 'ticker' => 'IMX'],
            ['name' => 'CryptoJournal', 'ticker' => 'CJC'],
            ['name' => 'Amygws', 'ticker' => 'AMY'],
            ['name' => 'Cubits', 'ticker' => 'QBT'],
            ['name' => 'EB3coin', 'ticker' => 'EB3'],
            ['name' => 'The Vegan Initiative', 'ticker' => 'XVE'],
            ['name' => 'Aptcoin', 'ticker' => 'APT'],
            ['name' => 'BlazerCoin', 'ticker' => 'BLAZR'],
            ['name' => 'Universe', 'ticker' => 'UNI'],
            ['name' => 'ECOcoin', 'ticker' => 'ECOC'],
            ['name' => 'Dark', 'ticker' => 'DARK'],
            ['name' => 'DonationCoin', 'ticker' => 'DON'],
            ['name' => 'Atmos', 'ticker' => 'ATMOS'],
            ['name' => 'HappyCoin', 'ticker' => 'HPC'],
            ['name' => 'Coinonat', 'ticker' => 'CXT'],
            ['name' => 'MacronCoin', 'ticker' => 'MCRN'],
            ['name' => 'Condensate', 'ticker' => 'RAIN'],
            ['name' => 'IvugeoEvolutionCoin', 'ticker' => 'IEC'],
            ['name' => 'Independent Money System', 'ticker' => 'IMS'],
            ['name' => 'ArgusCoin', 'ticker' => 'ARGUS'],
            ['name' => 'LomoCoin', 'ticker' => 'LMC'],
            ['name' => 'Bitcoin Scrypt', 'ticker' => 'BTCS'],
            ['name' => 'ProCurrency', 'ticker' => 'PROC'],
            ['name' => 'GoldReserve', 'ticker' => 'XGR'],
            ['name' => 'BenjiRolls', 'ticker' => 'BENJI'],
            ['name' => 'ParallelCoin', 'ticker' => 'DUO'],
            ['name' => 'GrowthCoin', 'ticker' => 'GRW'],
            ['name' => 'ILCoin', 'ticker' => 'ILC'],
            ['name' => 'Prizm', 'ticker' => 'PZM'],
            ['name' => 'Phreak', 'ticker' => 'PHR'],
            ['name' => 'PupaCoin', 'ticker' => 'PUPA'],
            ['name' => 'RiceCoin', 'ticker' => 'RICE'],
            ['name' => 'C-Bits', 'ticker' => 'XCT'],
            ['name' => 'Degas Coin', 'ticker' => 'DEA'],
            ['name' => 'ZSEcoin', 'ticker' => 'ZSE'],
            ['name' => 'TappingCoin', 'ticker' => 'TAP'],
            ['name' => 'MilkCoin', 'ticker' => 'MUU'],
            ['name' => 'Infinium-8', 'ticker' => 'INF8'],
            ['name' => 'HTML5 Coin', 'ticker' => 'HTML5'],
            ['name' => 'Subscriptio', 'ticker' => 'SBSC'],
            ['name' => 'Ultimate Secure Cash', 'ticker' => 'USC'],
            ['name' => 'DuxCoin', 'ticker' => 'DUX'],
            ['name' => 'PoisonIvyCoin', 'ticker' => 'XPS'],
            ['name' => 'EquiTrader', 'ticker' => 'EQT'],
            ['name' => 'Manet Coin', 'ticker' => 'MNTC'],
            ['name' => 'HamsterCoin', 'ticker' => 'HAMS'],
            ['name' => 'QTUM', 'ticker' => 'QTUM'],
            ['name' => 'NefariousCoin', 'ticker' => 'NEF'],
            ['name' => 'Quantum Resistant Ledger', 'ticker' => 'QRL'],
            ['name' => 'Espers', 'ticker' => 'ESP'],
            ['name' => 'Dynamic', 'ticker' => 'DYN'],
            ['name' => 'Nano', 'ticker' => 'NANO'],
            ['name' => 'ChanCoin', 'ticker' => 'CHAN'],
            ['name' => 'Dinastycoin', 'ticker' => 'DCY'],
            ['name' => 'Denarius', 'ticker' => 'DNR'],
            ['name' => 'DigitalPrice', 'ticker' => 'DP'],
            ['name' => 'Virta Unique Coin', 'ticker' => 'VUC'],
            ['name' => 'Bitcoin Planet', 'ticker' => 'BTPL'],
            ['name' => 'Unify', 'ticker' => 'UNIFY'],
            ['name' => 'BritCoin', 'ticker' => 'BRIT'],
            ['name' => 'SocialCoin', 'ticker' => 'SOCC'],
            ['name' => 'Octanox', 'ticker' => 'OTX'],
            ['name' => 'ArcticCoin', 'ticker' => 'ARC'],
            ['name' => 'Bogcoin', 'ticker' => 'BOG'],
            ['name' => 'BeachCoin', 'ticker' => 'SAND'],
            ['name' => 'DAS', 'ticker' => 'DAS'],
            ['name' => 'Linda', 'ticker' => 'LINDA'],
            ['name' => 'LeviarCoin', 'ticker' => 'XLC'],
            ['name' => 'DeepOnion', 'ticker' => 'ONION'],
            ['name' => 'Bitcore', 'ticker' => 'BTX'],
            ['name' => 'gCn Coin', 'ticker' => 'GCN'],
            ['name' => 'SmartCash', 'ticker' => 'SMART'],
            ['name' => 'Signatum', 'ticker' => 'SIGT'],
            ['name' => 'Onix', 'ticker' => 'ONX'],
            ['name' => 'Wink', 'ticker' => 'WINK'],
            ['name' => 'Cream', 'ticker' => 'CRM'],
            ['name' => 'Bitcoin Cash', 'ticker' => 'BCH'],
            ['name' => 'Bitmxittz', 'ticker' => 'BMXT'],
            ['name' => 'Monoeci', 'ticker' => 'XMCC'],
            ['name' => 'CampusCoin', 'ticker' => 'CMPCO'],
            ['name' => 'Draftcoin', 'ticker' => 'DFT'],
            ['name' => 'Vechain', 'ticker' => 'VET'],
            ['name' => 'Sojourn Coin', 'ticker' => 'SOJ'],
            ['name' => 'Stakecoin', 'ticker' => 'STCN'],
            ['name' => 'NewYorkCoin', 'ticker' => 'NYC'],
            ['name' => 'LiteBitcoin', 'ticker' => 'LBTC'],
            ['name' => 'FrazCoin', 'ticker' => 'FRAZ'],
            ['name' => 'Kronecoin', 'ticker' => 'KRONE'],
            ['name' => 'AdCoin', 'ticker' => 'ACC'],
            ['name' => 'Linx', 'ticker' => 'LINX'],
            ['name' => 'CoinonatX', 'ticker' => 'XCXT'],
            ['name' => 'BlakeStar', 'ticker' => 'BLAS'],
            ['name' => 'Ethereum Dark', 'ticker' => 'ETHD'],
            ['name' => 'Sumokoin', 'ticker' => 'SUMO'],
            ['name' => 'Obsidian', 'ticker' => 'ODN'],
            ['name' => 'Cardano', 'ticker' => 'ADA'],
            ['name' => 'Regalcoin', 'ticker' => 'REC'],
            ['name' => 'BitcoinZ', 'ticker' => 'BTCZ'],
            ['name' => 'NetM', 'ticker' => 'NTM'],
            ['name' => 'TrezarCoin', 'ticker' => 'TZC'],
            ['name' => 'Elements', 'ticker' => 'ELM'],
            ['name' => 'TerraNovaCoin', 'ticker' => 'TER'],
            ['name' => 'VIVO Coin', 'ticker' => 'VIVO'],
            ['name' => 'RG Coin', 'ticker' => 'RGC'],
            ['name' => 'Rupee', 'ticker' => 'RUP'],
            ['name' => 'Bitcoin Gold', 'ticker' => 'BTG'],
            ['name' => 'WomenCoin', 'ticker' => 'WOMEN'],
            ['name' => 'Theresa May Coin', 'ticker' => 'MAY'],
            ['name' => 'Eddie coin', 'ticker' => 'EDDIE'],
            ['name' => 'NamoCoin', 'ticker' => 'NAMO'],
            ['name' => 'LUXCoin', 'ticker' => 'LUX'],
            ['name' => 'Pirl', 'ticker' => 'PIRL'],
            ['name' => 'Xios', 'ticker' => 'XIOS'],
            ['name' => 'Bitcloud 2.0', 'ticker' => 'BTDX'],
            ['name' => 'eBoost', 'ticker' => 'EBST'],
            ['name' => 'KekCoin', 'ticker' => 'KEK'],
            ['name' => 'BlackholeCoin', 'ticker' => 'BLHC'],
            ['name' => 'AltCommunity Coin', 'ticker' => 'ALTCOM'],
            ['name' => 'Pure', 'ticker' => 'PURE'],
            ['name' => 'Rupaya', 'ticker' => 'RUPX'],
            ['name' => 'Infinity Economics', 'ticker' => 'XIN'],
            ['name' => 'Huncoin', 'ticker' => 'HNCN'],
            ['name' => 'MadCoin', 'ticker' => 'MADC'],
            ['name' => 'Pura', 'ticker' => 'PURA'],
            ['name' => 'Innova', 'ticker' => 'INN'],
            ['name' => 'Bitdeal', 'ticker' => 'BDL'],
            ['name' => 'WiserCoin', 'ticker' => 'WSC'],
            ['name' => 'Masari', 'ticker' => 'MSR'],
            ['name' => 'Ellaism', 'ticker' => 'ELLA'],
            ['name' => 'Sakuracoin', 'ticker' => 'SKR'],
            ['name' => 'Interstellar Holdings', 'ticker' => 'ISH'],
            ['name' => 'GoByte', 'ticker' => 'GBX'],
            ['name' => 'Castle', 'ticker' => 'CSTL'],
            ['name' => 'Insta Cash Coin', 'ticker' => 'ICC'],
            ['name' => 'Alqo', 'ticker' => 'ALQO'],
            ['name' => 'KingN Coin', 'ticker' => 'KNGN'],
            ['name' => 'Magnet', 'ticker' => 'MAG'],
            ['name' => 'Lamden Tau', 'ticker' => 'TAU'],
            ['name' => 'Electra', 'ticker' => 'ECA'],
            ['name' => 'Bitcoin Diamond', 'ticker' => 'BCD'],
            ['name' => 'Votecoin', 'ticker' => 'VOT'],
            ['name' => 'SHIELD', 'ticker' => 'XSH'],
            ['name' => 'BridgeCoin', 'ticker' => 'BCO*'],
            ['name' => 'Desire', 'ticker' => 'DSR'],
            ['name' => 'Mutual Coin', 'ticker' => 'MUT'],
            ['name' => 'Cash & Back Coin', 'ticker' => 'CNBC'],
            ['name' => 'UltraNote', 'ticker' => 'XUN'],
            ['name' => 'People', 'ticker' => 'MAN'],
            ['name' => 'Achain', 'ticker' => 'ACHN'],
            ['name' => 'Neuro', 'ticker' => 'NRO'],
            ['name' => 'Social Send', 'ticker' => 'SEND'],
            ['name' => 'BitCoal', 'ticker' => 'COAL'],
            ['name' => 'DaxxCoin', 'ticker' => 'DAXX'],
            ['name' => 'Bulwark', 'ticker' => 'BWK'],
            ['name' => 'BoxyCoin', 'ticker' => 'BOXY'],
            ['name' => 'Super Bitcoin', 'ticker' => 'SBTC'],
            ['name' => 'Kalkulus', 'ticker' => 'KLKS'],
            ['name' => 'AC3', 'ticker' => 'AC3'],
            ['name' => 'CHIPS', 'ticker' => 'CHIPS'],
            ['name' => 'Lethean', 'ticker' => 'LTHN'],
            ['name' => 'GermanCoin', 'ticker' => 'GER'],
            ['name' => 'LiteCoin Ultra', 'ticker' => 'LTCU'],
            ['name' => 'Straks', 'ticker' => 'STAK'],
            ['name' => 'PopularCoin', 'ticker' => 'POP'],
            ['name' => 'PhantomX', 'ticker' => 'PNX'],
            ['name' => 'HomeBlockCoin', 'ticker' => 'HBC'],
            ['name' => 'HTML Coin', 'ticker' => 'HTML'],
            ['name' => 'Photon', 'ticker' => 'PHO'],
            ['name' => 'Sucre', 'ticker' => 'SUCR'],
            ['name' => 'Accolade', 'ticker' => 'ACCO'],
            ['name' => 'CompuCoin', 'ticker' => 'CPN'],
            ['name' => 'Fantasy Cash', 'ticker' => 'XFT'],
            ['name' => 'OmiseGO Classic', 'ticker' => 'OMGC'],
            ['name' => 'Galactrum', 'ticker' => 'ORE'],
            ['name' => 'SparksPay', 'ticker' => 'SPK'],
            ['name' => 'GoaCoin', 'ticker' => 'GOA'],
            ['name' => 'Digiwage', 'ticker' => 'WAGE'],
            ['name' => 'GunCoin', 'ticker' => 'GUN'],
            ['name' => 'PolisPay', 'ticker' => 'POLIS'],
            ['name' => 'IrishCoin', 'ticker' => 'IRL'],
            ['name' => 'Trollcoin', 'ticker' => 'TROLL'],
            ['name' => 'Litecoin Plus', 'ticker' => 'LCP'],
            ['name' => 'TheGCCcoin', 'ticker' => 'TGCC'],
            ['name' => 'Monkey Project', 'ticker' => 'MONK'],
            ['name' => 'KZCash', 'ticker' => 'KZC'],
            ['name' => 'World Crypto Gold', 'ticker' => 'WCG'],
            ['name' => 'ECC', 'ticker' => 'ECC'],
            ['name' => 'Steneum Coin', 'ticker' => 'STN'],
            ['name' => 'Pioneer Coin', 'ticker' => 'PCOIN'],
            ['name' => 'UnitedBitcoin', 'ticker' => 'UBTC'],
            ['name' => 'Interzone', 'ticker' => 'ITZ'],
            ['name' => 'Black Pearl Coin', 'ticker' => 'XBP'],
            ['name' => 'Sigil', 'ticker' => 'SGL'],
            ['name' => 'OP Coin', 'ticker' => 'OPC'],
            ['name' => 'Shacoin', 'ticker' => 'SHA'],
            ['name' => 'BitWhite', 'ticker' => 'BTW'],
            ['name' => 'Croat', 'ticker' => 'CROAT'],
            ['name' => 'Valorbit', 'ticker' => 'VAL'],
            ['name' => 'TokenPay', 'ticker' => 'TPAY'],
            ['name' => 'Crave-NG', 'ticker' => 'CVNG'],
            ['name' => '1717 Masonic Commemorative Token', 'ticker' => 'MCT'],
            ['name' => 'Crypto Wisdom Coin', 'ticker' => 'CWIS'],
            ['name' => 'My Big Coin', 'ticker' => 'MBC'],
            ['name' => 'WorldBTC', 'ticker' => 'WOBTC'],
            ['name' => 'TurtleCoin', 'ticker' => 'TRTL'],
            ['name' => 'NeedleCoin', 'ticker' => 'NDLC'],
            ['name' => 'MUNcoin', 'ticker' => 'MUN'],
            ['name' => 'Unified Society USDEX', 'ticker' => 'USX'],
            ['name' => 'Bitcoin Atom', 'ticker' => 'BCA'],
            ['name' => 'SegWit2x', 'ticker' => 'B2X'],
            ['name' => 'Niobio Cash', 'ticker' => 'NBR'],
            ['name' => 'Scooby coin', 'ticker' => 'SCOOBY'],
            ['name' => 'BunnyCoin', 'ticker' => 'BUN'],
            ['name' => 'BitSoar Coin', 'ticker' => 'BSR'],
            ['name' => 'Pirate Blocks', 'ticker' => 'SKULL'],
            ['name' => 'Bitcoin Private', 'ticker' => 'BTCP'],
            ['name' => 'Skeincoin', 'ticker' => 'SKC'],
            ['name' => 'Karma', 'ticker' => 'KRM'],
            ['name' => 'Bitcoin Candy', 'ticker' => 'CDY'],
            ['name' => 'ShareChain', 'ticker' => 'SSS'],
            ['name' => 'Credence Coin', 'ticker' => 'CRDNC'],
            ['name' => 'Travelflex', 'ticker' => 'TRF'],
            ['name' => 'KREDS', 'ticker' => 'KREDS'],
            ['name' => 'Vulcano', 'ticker' => 'VULC'],
            ['name' => 'Tokyo Coin', 'ticker' => 'TOKC'],
            ['name' => 'BiblePay', 'ticker' => 'BBP'],
            ['name' => 'LitecoinCash', 'ticker' => 'LCC'],
            ['name' => 'BitFlip', 'ticker' => 'FLIP'],
            ['name' => 'LottoCoin', 'ticker' => 'LOT'],
            ['name' => 'Cypherfunks Coin', 'ticker' => 'FUNK'],
            ['name' => 'LeafCoin', 'ticker' => 'LEAF'],
            ['name' => 'BashCoin', 'ticker' => 'BASHC'],
            ['name' => 'DigiMoney', 'ticker' => 'DGM'],
            ['name' => 'Cerberus', 'ticker' => 'CBS'],
            ['name' => 'Bitcoin Hush', 'ticker' => 'BTCH'],
            ['name' => 'Lizus Payment', 'ticker' => 'LIZ'],
            ['name' => 'Crypto Improvement Fund', 'ticker' => 'CIF'],
            ['name' => 'Stipend', 'ticker' => 'SPD'],
            ['name' => 'Poa Network', 'ticker' => 'POA'],
            ['name' => 'Pushi', 'ticker' => 'PUSHI'],
            ['name' => 'PokerCoin', 'ticker' => 'POKER'],
            ['name' => 'Ellerium', 'ticker' => 'ELP'],
            ['name' => 'Velox', 'ticker' => 'VLX'],
            ['name' => 'Ontology', 'ticker' => 'ONT'],
            ['name' => 'Callisto Network', 'ticker' => 'CLO'],
            ['name' => 'Curium', 'ticker' => 'CRU'],
            ['name' => 'Elicoin', 'ticker' => 'ELIC'],
            ['name' => 'BitTube', 'ticker' => 'TUBE'],
            ['name' => 'Dinero', 'ticker' => 'DIN'],
            ['name' => 'Poseidon', 'ticker' => 'PSD'],
            ['name' => 'Lelecoin', 'ticker' => 'LELE'],
            ['name' => 'Akroma', 'ticker' => 'AKA'],
            ['name' => 'Manna', 'ticker' => 'MANNA'],
            ['name' => 'Aidos Kuneen', 'ticker' => 'ADK'],
            ['name' => 'Seraph', 'ticker' => 'SERA'],
            ['name' => 'AfterEther', 'ticker' => 'AET'],
            ['name' => 'Cosmo', 'ticker' => 'CMOS'],
            ['name' => 'Reden', 'ticker' => 'REDN'],
            ['name' => 'TulipCoin', 'ticker' => 'TLP'],
            ['name' => 'Bitspace', 'ticker' => 'BSX'],
            ['name' => 'Fonero', 'ticker' => 'FNO'],
            ['name' => 'Snowgem', 'ticker' => 'XSG'],
            ['name' => 'CavatCoin', 'ticker' => 'CVTC'],
            ['name' => 'Stellite', 'ticker' => 'XTL'],
            ['name' => 'Briacoin', 'ticker' => 'BRIA'],
            ['name' => 'Ignition', 'ticker' => 'IC'],
            ['name' => 'MoneyBag', 'ticker' => 'MNB'],
            ['name' => 'Bitrolium', 'ticker' => 'BTL'],
            ['name' => 'Bitcoin Interest', 'ticker' => 'BCI'],
            ['name' => 'MedicCoin', 'ticker' => 'MEDIC'],
            ['name' => 'FOLM coin', 'ticker' => 'FLM'],
            ['name' => 'Alpenschillling', 'ticker' => 'ALPS'],
            ['name' => 'Zelcash', 'ticker' => 'ZEL'],
            ['name' => 'Bitcoin Green', 'ticker' => 'BITG'],
            ['name' => 'Deviant Coin', 'ticker' => 'DEV'],
            ['name' => 'Abjcoin', 'ticker' => 'ABJ'],
            ['name' => 'Rapture', 'ticker' => 'RAP'],
            ['name' => 'Animecoin', 'ticker' => 'ANI'],
            ['name' => 'Profit Hunters Coin', 'ticker' => 'PHC'],
            ['name' => 'Semux', 'ticker' => 'SEM'],
            ['name' => 'BitBlocks', 'ticker' => 'BBK'],
            ['name' => 'Uwezocoin', 'ticker' => 'UWC'],
            ['name' => 'FuturoCoin', 'ticker' => 'FTO'],
            ['name' => 'Carebit', 'ticker' => 'CARE'],
            ['name' => 'Zealium', 'ticker' => 'NZL'],
            ['name' => 'Monero Classic', 'ticker' => 'XMC'],
            ['name' => 'FedoraCoin', 'ticker' => 'TIPS'],
            ['name' => 'Charm Coin', 'ticker' => 'CHARM'],
            ['name' => 'Proton', 'ticker' => 'PROTON'],
            ['name' => 'Dero', 'ticker' => 'DERO'],
            ['name' => 'iDealCash', 'ticker' => 'DEAL'],
            ['name' => 'Jumpcoin', 'ticker' => 'JUMP'],
            ['name' => 'Infinex', 'ticker' => 'INFX'],
            ['name' => 'Bitcoin Incognito', 'ticker' => 'XBI'],
            ['name' => 'KEYCO', 'ticker' => 'KEC'],
            ['name' => 'SABR Coin', 'ticker' => 'SABR'],
            ['name' => 'HollyWoodCoin', 'ticker' => 'HWC'],
            ['name' => 'GINcoin', 'ticker' => 'GIN'],
            ['name' => 'MoneroV', 'ticker' => 'XMV'],
            ['name' => 'Parlay', 'ticker' => 'PAR'],
            ['name' => 'Listerclassic Coin', 'ticker' => 'LTCC'],
            ['name' => 'Amero', 'ticker' => 'AMX'],
            ['name' => 'PlatinCoin', 'ticker' => 'PLTC'],
            ['name' => 'BetKings', 'ticker' => 'KNG'],
            ['name' => 'Cognitio', 'ticker' => 'COG'],
            ['name' => 'BitCOEN', 'ticker' => 'BEN'],
            ['name' => 'Loki', 'ticker' => 'LOKI'],
            ['name' => 'Newton Coin', 'ticker' => 'NCP'],
            ['name' => 'Staxcoin', 'ticker' => 'STAX'],
            ['name' => 'Mercoin', 'ticker' => 'MRN'],
            ['name' => 'Swisscoin', 'ticker' => 'SIC'],
            ['name' => 'ExchangeCoin', 'ticker' => 'EXCC'],
            ['name' => 'Reliance', 'ticker' => 'REL'],
            ['name' => 'BitcoiNote', 'ticker' => 'BTCN'],
            ['name' => 'Xt3ch', 'ticker' => 'XT3'],
            ['name' => 'MassGrid', 'ticker' => 'MGD'],
            ['name' => 'TheVig', 'ticker' => 'VIG'],
            ['name' => 'PluraCoin', 'ticker' => 'PLURA'],
            ['name' => 'EmaratCoin', 'ticker' => 'EMAR'],
            ['name' => 'XtendCash', 'ticker' => 'XTNC'],
            ['name' => 'Rover Coin', 'ticker' => 'ROE'],
            ['name' => 'LitecoinPro', 'ticker' => 'LTCP'],
            ['name' => 'Dekado', 'ticker' => 'DKD'],
            ['name' => 'Lynx', 'ticker' => 'LYNX'],
            ['name' => 'Poseidon Quark', 'ticker' => 'POSQ'],
            ['name' => 'MYCE', 'ticker' => 'YCE'],
            ['name' => 'Arionum', 'ticker' => 'ARO'],
            ['name' => 'BitcoinWSpectrum', 'ticker' => 'BWS'],
            ['name' => 'Bitcoin Core', 'ticker' => 'BTCC'],
            ['name' => 'GolfCoin', 'ticker' => 'GOLF'],
            ['name' => 'Muse', 'ticker' => 'MUSE'],
            ['name' => 'Motion', 'ticker' => 'XMN'],
            ['name' => 'PlusOneCoin', 'ticker' => 'PLUS1'],
            ['name' => 'Axe', 'ticker' => 'AXE'],
            ['name' => 'GambleCoin', 'ticker' => 'GMCN'],
            ['name' => 'Trivechain', 'ticker' => 'TRVC'],
            ['name' => 'Dystem', 'ticker' => 'DTEM'],
            ['name' => 'Giant', 'ticker' => 'GIC'],
            ['name' => 'Peony Coin', 'ticker' => 'PNY'],
            ['name' => 'SafeCoin', 'ticker' => 'SAFE'],
            ['name' => 'Absolute Coin', 'ticker' => 'ABS'],
            ['name' => 'Vitae', 'ticker' => 'VITAE'],
            ['name' => 'Bitcoin Supreme', 'ticker' => 'BSPM'],
            ['name' => 'GenesisX', 'ticker' => 'XGS'],
            ['name' => 'BitminerCoin', 'ticker' => 'BIM'],
            ['name' => 'HexCoin', 'ticker' => 'HEX'],
            ['name' => 'Deimos', 'ticker' => 'DEI'],
            ['name' => 'TPCash', 'ticker' => 'TPC'],
            ['name' => 'Oyster Platform', 'ticker' => 'OYS'],
            ['name' => 'Webchain', 'ticker' => 'WEBC'],
            ['name' => 'Ryo', 'ticker' => 'RYO'],
            ['name' => 'MUSDcoin', 'ticker' => 'MUSD'],
            ['name' => 'Urals Coin', 'ticker' => 'URALS'],
            ['name' => 'Qwertycoin', 'ticker' => 'QWC'],
            ['name' => 'Bitcoin Nova', 'ticker' => 'BITN'],
            ['name' => 'ARENON', 'ticker' => 'ARE'],
            ['name' => 'DACash', 'ticker' => 'DACASH'],
            ['name' => 'EUNO', 'ticker' => 'EUNO'],
            ['name' => 'MMOCoin', 'ticker' => 'MMO'],
            ['name' => 'DasCoin', 'ticker' => 'DASC'],
            ['name' => 'Ketan', 'ticker' => 'KETAN'],
            ['name' => 'NIX', 'ticker' => 'NIX'],
            ['name' => 'Italocoin', 'ticker' => 'ITA'],
            ['name' => 'Safe Trade Coin', 'ticker' => 'XSTC'],
            ['name' => 'Project Pai', 'ticker' => 'PPAI'],
            ['name' => 'Mont Blanc', 'ticker' => 'MBLC'],
            ['name' => 'XDNA', 'ticker' => 'XDNA'],
            ['name' => 'PAXEX', 'ticker' => 'PAXEX'],
            ['name' => 'Ditcoin', 'ticker' => 'DIT'],
            ['name' => 'Azart', 'ticker' => 'AZART'],
            ['name' => 'Averopay', 'ticker' => 'AOP'],
            ['name' => 'Apollon', 'ticker' => 'XAP'],
            ['name' => 'ThunderStake', 'ticker' => 'TSC'],
            ['name' => 'SimpleBank', 'ticker' => 'SPLB'],
            ['name' => 'Harvest Masternode Coin', 'ticker' => 'HMN'],
            ['name' => 'Kcash', 'ticker' => 'KCASH'],
            ['name' => 'Xchange', 'ticker' => 'XCG'],
            ['name' => 'Acute Angle Cloud', 'ticker' => 'AAC'],
            ['name' => 'StarKST', 'ticker' => 'KST'],
            ['name' => 'Aukcecoin', 'ticker' => 'AUK'],
            ['name' => 'Plancoin', 'ticker' => 'PLAN'],
            ['name' => 'Traid', 'ticker' => 'TRAID'],
            ['name' => 'Teachers Blockchain', 'ticker' => 'TCHB'],
            ['name' => 'MIODIOCOIN', 'ticker' => 'MIODIO'],
            ['name' => 'Lightpaycoin', 'ticker' => 'LTPC'],
            ['name' => 'Hanacoin', 'ticker' => 'HANA'],
            ['name' => 'Bitvote', 'ticker' => 'BTV'],
            ['name' => 'CrypticCoin', 'ticker' => 'CRYP'],
            ['name' => 'Bettex coin', 'ticker' => 'BTXC'],
            ['name' => 'ZestCoin', 'ticker' => 'ZEST'],
            ['name' => 'X-CASH', 'ticker' => 'XCASH'],
            ['name' => 'Brazio', 'ticker' => 'BRAZ'],
            ['name' => 'Actinium', 'ticker' => 'ACM'],
            ['name' => 'Litecoinz', 'ticker' => 'LTZ'],
            ['name' => 'ETHER-1', 'ticker' => 'ETHO'],
            ['name' => 'TWIST', 'ticker' => 'TWISTR'],
            ['name' => 'MicroBitcoin', 'ticker' => 'MBTC'],
            ['name' => 'FOREXCOIN', 'ticker' => 'FOREX'],
            ['name' => 'Bitcoin SV', 'ticker' => 'BSV'],
            ['name' => 'DACH Coin', 'ticker' => 'DACH'],
            ['name' => 'Argoneum', 'ticker' => 'AGM'],
            ['name' => '2Acoin', 'ticker' => 'ARMS'],
            ['name' => 'BitMoney', 'ticker' => 'BITM'],
            ['name' => 'Bitcoiin2Gen', 'ticker' => 'B2G'],
            ['name' => 'Auxilium', 'ticker' => 'AUX'],
            ['name' => 'Junson Ming Chan Coin', 'ticker' => 'JMC'],
            ['name' => 'FREDEnergy', 'ticker' => 'FRED'],
            ['name' => 'Zenad', 'ticker' => 'ZND'],
            ['name' => 'Ngin', 'ticker' => 'NGIN'],
            ['name' => 'Genesis Network', 'ticker' => 'GENX'],
            ['name' => 'Vertical', 'ticker' => 'VTL'],
            ['name' => 'C25 Coin', 'ticker' => 'C25'],
            ['name' => 'HerbCoin', 'ticker' => 'HERB'],
            ['name' => 'Aquachain', 'ticker' => 'AQUA'],
            ['name' => 'BlakeBitcoin', 'ticker' => 'BBTC'],
            ['name' => 'Universal Molecule', 'ticker' => 'UMO'],
            ['name' => 'Lithium', 'ticker' => 'LIT'],
            ['name' => 'Electron', 'ticker' => 'ELT'],
            ['name' => 'Xeonbit', 'ticker' => 'XNB'],
            ['name' => 'Smart Bitcoin', 'ticker' => 'RBTC'],
            ['name' => 'PirateCash', 'ticker' => 'PIRATE'],
            ['name' => 'Exosis', 'ticker' => 'EXO'],
            ['name' => 'Block-Logic', 'ticker' => 'BLTG'],
            ['name' => 'MIMI Money', 'ticker' => 'MIMI'],
            ['name' => 'Oduwa', 'ticker' => 'OWC'],
            ['name' => 'Beam', 'ticker' => 'BEAM'],
            ['name' => 'Galilel', 'ticker' => 'GALI'],
            ['name' => 'Zaddex', 'ticker' => 'ZEX'],
            ['name' => 'Bithereum', 'ticker' => 'BTH'],
            ['name' => 'ArQmA', 'ticker' => 'ARQ'],
            ['name' => 'Amoveo', 'ticker' => 'VEO'],
            ['name' => 'Crypto Sports', 'ticker' => 'CSPN'],
            ['name' => 'Credit', 'ticker' => 'CREDIT'],
            ['name' => 'Scribe Network', 'ticker' => 'SCRIBE'],
            ['name' => 'LYTIX', 'ticker' => 'LYTX'],
            ['name' => 'SiaClassic', 'ticker' => 'SCA'],
            ['name' => 'Lunes', 'ticker' => 'LUNES'],
            ['name' => 'SLICE', 'ticker' => 'SLC'],
            ['name' => 'Dash Platinum', 'ticker' => 'DASHP'],
            ['name' => 'Nasdacoin', 'ticker' => 'NSD'],
            ['name' => 'Vidulum', 'ticker' => 'VDL'],
            ['name' => 'Beetle Coin', 'ticker' => 'BEET'],
            ['name' => 'Titan Coin', 'ticker' => 'TTN'],
            ['name' => 'Award', 'ticker' => 'AWR'],
            ['name' => 'BlockStamp', 'ticker' => 'BST'],
            ['name' => 'BLAST', 'ticker' => 'BLAST'],
            ['name' => 'ESBC', 'ticker' => 'ESBC'],
            ['name' => 'VeriBlock', 'ticker' => 'VBK'],
            ['name' => 'Bitcoin Rhodium', 'ticker' => 'XRC'],
            ['name' => 'GlobalToken', 'ticker' => 'GLT'],
            ['name' => 'Insane Coin', 'ticker' => 'INSN'],
            ['name' => 'WRTcoin', 'ticker' => 'WRT'],
            ['name' => 'ALAX', 'ticker' => 'ALX'],
            ['name' => 'The Freedom Coin', 'ticker' => 'TFC'],
            ['name' => 'AmberCoin', 'ticker' => 'AMBER'],
            ['name' => 'LiteDoge', 'ticker' => 'LDOGE'],
            ['name' => 'Boolberry', 'ticker' => 'BBR'],
            ['name' => 'SolarCoin', 'ticker' => 'SLR'],
            ['name' => 'TruckCoin', 'ticker' => 'TRK'],
            ['name' => 'UFO Coin', 'ticker' => 'UFO'],
            ['name' => 'Ascension Coin', 'ticker' => 'ASN'],
            ['name' => 'OrangeCoin', 'ticker' => 'OC'],
            ['name' => 'GSM Coin', 'ticker' => 'GSM'],
            ['name' => 'BlakeCoin', 'ticker' => 'BLC'],
            ['name' => 'BitstarCoin', 'ticker' => 'BITS'],
            ['name' => 'NeosCoin', 'ticker' => 'NEOS'],
            ['name' => 'HyperCoin', 'ticker' => 'HYPER'],
            ['name' => 'PinkCoin', 'ticker' => 'PINK'],
            ['name' => 'FantomCoin', 'ticker' => 'FCN'],
            ['name' => 'World Trade Funds', 'ticker' => 'XWT'],
            ['name' => 'Crypto Escudo', 'ticker' => 'CESC'],
            ['name' => 'Twelve Coin', 'ticker' => 'TWLV'],
            ['name' => 'AudioCoin', 'ticker' => 'ADC'],
            ['name' => 'Wood Coin', 'ticker' => 'LOG'],
            ['name' => 'Cerium', 'ticker' => 'XCE'],
            ['name' => 'IncaKoin', 'ticker' => 'NKA'],
            ['name' => 'Piggy Coin', 'ticker' => 'PIGGY'],
            ['name' => 'Crown Coin', 'ticker' => 'CRW'],
            ['name' => 'Genstake', 'ticker' => 'GEN'],
            ['name' => 'Litestar Coin', 'ticker' => 'LTS'],
            ['name' => 'Quazar Coin', 'ticker' => 'QCN'],
            ['name' => 'SmileyCoin', 'ticker' => 'SMLY'],
            ['name' => 'BitQuark', 'ticker' => 'BTQ'],
            ['name' => 'ParkByte', 'ticker' => 'PKB'],
            ['name' => 'Hellenic Coin', 'ticker' => 'HNC'],
            ['name' => 'XiaoMiCoin', 'ticker' => 'MI'],
            ['name' => 'Groestlcoin', 'ticker' => 'GRS'],
            ['name' => 'CapriCoin', 'ticker' => 'CPC'],
            ['name' => 'ClubCoin', 'ticker' => 'CLUB'],
            ['name' => 'Radium', 'ticker' => 'RADS'],
            ['name' => 'Bata', 'ticker' => 'BTA'],
            ['name' => 'Pakcoin', 'ticker' => 'PAK'],
            ['name' => 'Creditbit', 'ticker' => 'CRB'],
            ['name' => 'OKCash', 'ticker' => 'OK'],
            ['name' => 'Lisk', 'ticker' => 'LSK'],
            ['name' => 'HiCoin', 'ticker' => 'XHI'],
            ['name' => 'WhiteCoin', 'ticker' => 'XWC'],
            ['name' => 'Dotcoin', 'ticker' => 'DOT'],
            ['name' => 'FriendshipCoin', 'ticker' => 'FSC'],
            ['name' => 'The Hempcoin', 'ticker' => 'THC'],
            ['name' => 'Fiii', 'ticker' => 'FIII'],
            ['name' => 'JoinCoin', 'ticker' => 'J'],
            ['name' => 'Triangles Coin', 'ticker' => 'TRI'],
            ['name' => 'RAIZER', 'ticker' => 'RAIZER'],
            ['name' => 'Vollar', 'ticker' => 'VOLLAR'],
            ['name' => 'VENOTY', 'ticker' => 'VNTY'],
            ['name' => 'AlphaX', 'ticker' => 'AX'],
            ['name' => 'Swinca', 'ticker' => 'SWI'],
            ['name' => 'TecraCoin', 'ticker' => 'TCR'],
            ['name' => 'HCX PAY', 'ticker' => 'HCXP'],
            ['name' => 'Gexan', 'ticker' => 'GEX'],
            ['name' => 'EOS', 'ticker' => 'EOS'],
            ['name' => 'Ahoolee', 'ticker' => 'AHT'],
            ['name' => 'Reality Clash', 'ticker' => 'RCC'],
            ['name' => 'Oxycoin', 'ticker' => 'OXY'],
            ['name' => 'Z2 Coin', 'ticker' => 'Z2'],
            ['name' => 'Kapu', 'ticker' => 'KAPU'],
            ['name' => 'Graft Blockchain', 'ticker' => 'GRFT'],
            ['name' => 'Monaize', 'ticker' => 'MNZ'],
            ['name' => 'Avesta', 'ticker' => 'AVE'],
            ['name' => 'Extreme Sportsbook', 'ticker' => 'XSB'],
            ['name' => 'Scorum', 'ticker' => 'SCRM'],
            ['name' => 'Local World Forwarders', 'ticker' => 'LWF'],
            ['name' => 'iOlite', 'ticker' => 'ILT'],
            ['name' => 'Adamant', 'ticker' => 'ADM'],
            ['name' => 'uPlexa', 'ticker' => 'UPX'],
            ['name' => 'TigerCash', 'ticker' => 'TCH'],
            ['name' => 'LAPO', 'ticker' => 'LAX'],
            ['name' => 'Tip Blockchain', 'ticker' => 'TIP'],
            ['name' => 'DECOIN', 'ticker' => 'DTEP'],
            ['name' => 'Waves', 'ticker' => 'WAVES'],
            ['name' => 'Particl', 'ticker' => 'PART'],
            ['name' => 'Slate', 'ticker' => 'SLX'],
            ['name' => 'ShardCoin', 'ticker' => 'SHARD'],
            ['name' => 'BitTorrent', 'ticker' => 'BTT'],
            ['name' => 'XAYA', 'ticker' => 'CHI'],
            ['name' => 'ChainZilla', 'ticker' => 'ZILLA'],
            ['name' => 'Nxt', 'ticker' => 'NXT'],
            ['name' => 'ZEPHYR', 'ticker' => 'ZEPH'],
            ['name' => 'Quotient', 'ticker' => 'XQN'],
            ['name' => 'NetworkCoin', 'ticker' => 'NETC'],
            ['name' => 'VapersCoin', 'ticker' => 'VPRC'],
            ['name' => 'Gapcoin', 'ticker' => 'GAP'],
            ['name' => 'Super Zero', 'ticker' => 'SERO'],
            ['name' => 'UOS', 'ticker' => 'UOS'],
            ['name' => 'Beldex', 'ticker' => 'BDX'],
            ['name' => 'Horizen', 'ticker' => 'ZEN'],
            ['name' => 'BitcoinPlus', 'ticker' => 'XBC'],
            ['name' => 'DivotyCoin', 'ticker' => 'DVTC'],
            ['name' => 'Giotto Coin', 'ticker' => 'GIOT'],
            ['name' => 'OpenSourceCoin', 'ticker' => 'OPSC'],
            ['name' => 'SteamPunk', 'ticker' => 'PUNK']
        ];
    }
}
