<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Repositories\AssetClassRepository;
use App\Repositories\AssetRepository;

class FiiSeeder extends Seeder
{
    protected $assetClassRepository;
    protected $assetRepository;

    public function __construct(AssetClassRepository $assetClassRepository, AssetRepository $assetRepository)
    {
        $this->assetClassRepository = $assetClassRepository;
        $this->assetRepository = $assetRepository;
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $assetClass = $this->assetClassRepository->getBySlug('fiis');

        foreach ($this->getData() as $data) {
            $asset = $this->assetRepository->getAssetByTicker($data['ticker']);

            if ($asset) {
                continue;
            }

            $this->assetRepository->createAsset([
                'asset_class_id' => $assetClass->id,
                'ticker' => $data['ticker']
            ]);
        }
    }

    public function getData(): array
    {
        return [
            ['name' => 'ARX DOVER RECEBÍVEIS FDO DE INV IMOB', 'ticker' => 'ARXD11'],
            ['name' => 'CANUMA CAPITAL MULTIESTRATÉGIA FDO DE INV IMOB', 'ticker' => 'CCME11'],
            ['name' => 'INTER TEVA INDICE DE TIJOLO FUNDO DE INVESTIMENTO', 'ticker' => 'ITIT11'],
            ['name' => 'JASC RENDA VAREJO ESSENCIAL FDO DE INV IMOB - FII', 'ticker' => 'JASC11'],
            ['name' => 'AF INVEST CRI FDO. INV. IMOB - RECEBÍVEIS IMOB.', 'ticker' => 'AFHI11'],
            ['name' => 'AJ MALLS FDO DE INV IMOB', 'ticker' => 'AJFI11'],
            ['name' => 'ALIANZA MULTIESTRATÉGIA FUNDO DE INVESTIMENTO IMOB', 'ticker' => 'ALZM11'],
            ['name' => 'ALIANZA MULTIOFFICES  - FDO. INV. IMOB', 'ticker' => 'MTOF11'],
            ['name' => 'ALIANZA TRUST RENDA IMOBILIARIA FDO INV IMOB', 'ticker' => 'ALZR11'],
            ['name' => 'ALIANZA URBAN HUB RENDA FUNDO DE INVESTIMENTO IMOB', 'ticker' => 'AURB11'],
            ['name' => 'AROEIRA 333 RENDA LOGÍSTICA FDO DE INV IMOB', 'ticker' => 'AROA11'],
            ['name' => 'ASA METROPOLIS FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'ASMT11'],
            ['name' => 'ASA RETROFITS I FDO DE INV IMOB - FII', 'ticker' => 'ASRF11'],
            ['name' => 'AUTONOMY EDIFÍCIOS CORPORATIVOS FUND. INV. IMOB.', 'ticker' => 'AIEC11'],
            ['name' => 'BANESTES RECEBÍVEIS IMOBILIÁRIOS FDO INV IMOB  FII', 'ticker' => 'BCRI11'],
            ['name' => 'BANRISUL NOVAS FRONTEIRAS FDO INV IMOB - FII', 'ticker' => 'BNFS11'],
            ['name' => 'BARZEL CD1 FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'BZEL11'],
            ['name' => 'BASÍLICA PARTNERS LED CORPORATE FDO INV IMOB FII', 'ticker' => 'BPLC11'],
            ['name' => 'BB FDO INV IMOB PROGRESSIVO', 'ticker' => 'BBFI11'],
            ['name' => 'BB FUNDO DE FUNDOS - FDO. INV. IMOB.', 'ticker' => 'BBFO11'],
            ['name' => 'BB RECEBIVEIS IMOBILIARIOS FDO INV IMOB - FII', 'ticker' => 'BBIM11'],
            ['name' => 'BB RENDA CORPORATIVA FDO INV IMOB - FII', 'ticker' => 'BBRC11'],
            ['name' => 'BB RENDA DE PAPÉIS IMOBILIÁRIOS FDO INV IMOB - FII', 'ticker' => 'RNDP11'],
            ['name' => 'BLUEMACAW LOGÍSTICA FDO. INVEST. IMOB.', 'ticker' => 'BLMG11'],
            ['name' => 'BR7 SENADO FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'BRSE11'],
            ['name' => 'BRADESCO CARTEIRA IMOBILIÁRIA ATIVA - FII', 'ticker' => 'BCIA11'],
            ['name' => 'BRAZIL REALTY FDO INV IMOB', 'ticker' => 'BZLI11'],
            ['name' => 'BRAZILIAN GRAVEYARD DEATH CARE FDO INV IMOB - FII', 'ticker' => 'CARE11'],
            ['name' => 'BRC RENDA CORPORATIVA FII', 'ticker' => 'FATN11'],
            ['name' => 'BRESCO LOGÍSTICA - FDO INV IMOB', 'ticker' => 'BRCO11'],
            ['name' => 'BRIO CRÉDITO ESTRUTURADO - FDO. INVEST. IMOB.', 'ticker' => 'BICE11'],
            ['name' => 'BRIO MULTIESTRATÉGIA FDO INV IMOB', 'ticker' => 'BIME11'],
            ['name' => 'BRIO REAL ESTATE II - FDO INV IMOB', 'ticker' => 'BRIM11'],
            ['name' => 'BRIO REAL ESTATE III FDO DE INVEST. IMOB.', 'ticker' => 'BRIP11'],
            ['name' => 'BRIO REAL ESTATE IV - FUNDO DE INVESTIMENTO IMOB', 'ticker' => 'BIPD11'],
            ['name' => 'BRIO REAL ESTATE V - FII', 'ticker' => 'BIPE11'],
            ['name' => 'BRIX FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'BRIX11'],
            ['name' => 'BRPR CORPORATE OFFICES FDO DE INV IMOB', 'ticker' => 'BROF11'],
            ['name' => 'BRPR E-TOWER FDO DE INV IMOB', 'ticker' => 'BETW11'],
            ['name' => 'BS2 ALLINVESTMENTS FDO DE INV IMOB', 'ticker' => 'LLAO11'],
            ['name' => 'BTG PACTUAL HOTÉIS FII', 'ticker' => 'BTHI11'],
            ['name' => 'BTG PACTUAL LOGISTICA FDO INV IMOB - FII', 'ticker' => 'BTLG11'],
            ['name' => 'BTOWERS FII - FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'BTWR11'],
            ['name' => 'BTSP I FDO. INVEST. IMOB - FII', 'ticker' => 'BTSG11'],
            ['name' => 'BTSP II FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'BTSI11'],
            ['name' => 'CAIXA RIO BRAVO FDO DE FDOS INV IMOB II', 'ticker' => 'CRFF11'],
            ['name' => 'CAIXA RIO BRAVO FUNDO DE FDO INV IMOB - FII', 'ticker' => 'CXRI11'],
            ['name' => 'CAPITÂNIA REIT FOF - FDO INV IMOB II', 'ticker' => 'CPFO11'],
            ['name' => 'CAPITÂNIA REIT FOF - FDO. INVEST. IMOB', 'ticker' => 'CPFF11'],
            ['name' => 'CAPITANIA SECURITIES II FDO INV IMOB - FII', 'ticker' => 'CPTS11'],
            ['name' => 'CARTESIA RECEBÍVEIS IMOBILIÁRIOS - FUNDO DE INVEST', 'ticker' => 'CACR11'],
            ['name' => 'CASTELLO BRANCO OFFICE PARK FDO INV IMOB - FII', 'ticker' => 'CBOP11'],
            ['name' => 'CATUAÍ VBI TRIPLE A FDO DE INV IMOB', 'ticker' => 'BLCA11'],
            ['name' => 'CF2 FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'CFHI11'],
            ['name' => 'CF3 FUNDO DE INVESTIMENTO IMOBILIÁRIO - FII', 'ticker' => 'CFII11'],
            ['name' => 'CIDADE JARDIM CONTINENAL TOWER FDO INV IMOB', 'ticker' => 'CJCT11'],
            ['name' => 'CIX RENDIMENTO FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'CIXR11'],
            ['name' => 'CLAVE ÍNDICES DE PREÇOS FDO DE INV IMOB', 'ticker' => 'CLIN11'],
            ['name' => 'CORPORATE OFFICE PROPERTIES FII - FDO DE INV IMOB', 'ticker' => 'COPP11'],
            ['name' => 'COSMIC FDO DE INV IMOB', 'ticker' => 'CSMC11'],
            ['name' => 'CSHG IMOB. FOF - FDO INV. IMOB. - FII', 'ticker' => 'HGFF11'],
            ['name' => 'CSHG LOGÍSTICA FDO INV IMOB - FII', 'ticker' => 'HGLG11'],
            ['name' => 'CSHG PRIME OFFICES FDO INV IMOB - FII', 'ticker' => 'HGPO11'],
            ['name' => 'CSHG REAL ESTATE FDO INV IMOB - FII', 'ticker' => 'HGRE11'],
            ['name' => 'CSHG RECEBÍVEIS IMOBILIÁRIOS FDO INV IMOB - FII', 'ticker' => 'HGCR11'],
            ['name' => 'CSHG RENDA URBANA - FDO INV IMOB - FII', 'ticker' => 'HGRU11'],
            ['name' => 'CSHG RESIDENCIAL FDO DE INV IMOB - FII', 'ticker' => 'HGRS11'],
            ['name' => 'CVPAR FUNDO DE INVESTIMENTO IMOBILIÁRIO DE CRI', 'ticker' => 'CVPR11'],
            ['name' => 'CYRELA CRÉDITO - FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'CYCR11'],
            ['name' => 'CYRELA DESENVOLVIMENTO LOGÍSTICO FDO INV IMOB', 'ticker' => 'CYLD11'],
            ['name' => 'DEL MONTE AJAX FDO INV IMOB - FII', 'ticker' => 'DLMT11'],
            ['name' => 'DEVANT PROPERTIES FUNDO DE INVESTIMENTO IMOB', 'ticker' => 'DPRO11'],
            ['name' => 'DEVANT RECEBÍVEIS IMOBILIÁRIOS FDO. INVEST. IMOB.', 'ticker' => 'DEVA11'],
            ['name' => 'DIAMANTE FDO INV IMOB', 'ticker' => 'DAMT11'],
            ['name' => 'DOVEL FDO INV IMOB', 'ticker' => 'DOVL11'],
            ['name' => 'ENERGY RESORT FDO. INVEST. IMOB.', 'ticker' => 'EGYR11'],
            ['name' => 'EQI RECEBÍVEIS IMOBILIÁRIOS FDO DE INV IMOBILIÁRIO', 'ticker' => 'EQIR11'],
            ['name' => 'ESTOQUE RESIDENCIAL E COMERCIAL RJ FDO INV IMOB', 'ticker' => 'ERCR11'],
            ['name' => 'EUROPA 105 - FDO INV IMOB', 'ticker' => 'ERPA11'],
            ['name' => 'EVEN II KINEA FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'KEVE11'],
            ['name' => 'EXES FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'EXES11'],
            ['name' => 'FARIA LIMA CAPITAL RECEB. IMOB. I - FDO INV. IMOB.', 'ticker' => 'FLCR11'],
            ['name' => 'FATOR RENDA GALPÃO FDO INV IMOB', 'ticker' => 'FAGL11'],
            ['name' => 'FATOR RENDA URBANA FDO DE INV IMOB', 'ticker' => 'FARU11'],
            ['name' => 'FATOR VERITA FDO INV IMOB - FII', 'ticker' => 'VRTA11'],
            ['name' => 'FDO BRASÍLIO MACHADO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'BMII11'],
            ['name' => 'FDO DE INV IMOB FATOR RENDA ESTRUTURADA', 'ticker' => 'FAOE11'],
            ['name' => 'FDO DE INV IMOB LEBLON REALTY DESENVOLVIMENTO I', 'ticker' => 'LRDI11'],
            ['name' => 'FDO DE INV IMOB MAUÁ CAPITAL HIGH YIELD - FII', 'ticker' => 'MCHY11'],
            ['name' => 'FDO DE INV IMOB MAUA CAPITAL MPD DESENV RESID', 'ticker' => 'MMPD11'],
            ['name' => 'FDO DE INV IMOB UNIMED INVESTCOOP NAC', 'ticker' => 'UMED11'],
            ['name' => 'FDO DE INV IMOBILIÁRIO DE CRI INTEGRAL BREI', 'ticker' => 'IBCR11'],
            ['name' => 'FDO DE INV IMOBILIÁRIO DE UNIDADES AUTÔNOMAS II', 'ticker' => 'IDGR11'],
            ['name' => 'FDO DE INVEST IMOB GUARDIAN MULTIESTRATÉGIA I', 'ticker' => 'GAME11'],
            ['name' => 'FDO DE INVEST IMOB TELLUS RIO BRAVO RENDA LOGISTIC', 'ticker' => 'TRBL11'],
            ['name' => 'FDO INV IMOB - FII ANCAR IC', 'ticker' => 'ANCR11'],
            ['name' => 'FDO INV IMOB - FII ANHANGUERA EDUCACIONAL', 'ticker' => 'FAED11'],
            ['name' => 'FDO INV IMOB - FII BM BRASCAN LAJES CORPORATIVAS', 'ticker' => 'BMLC11'],
            ['name' => 'FDO INV IMOB - FII BRLPROP', 'ticker' => 'BPRP11'],
            ['name' => 'FDO INV IMOB - FII BTG PACTUAL CORP. OFFICE FUND', 'ticker' => 'BRCR11'],
            ['name' => 'FDO INV IMOB - FII BTG PACTUAL FUNDO DE FUNDOS', 'ticker' => 'BCFF11'],
            ['name' => 'FDO INV IMOB - FII CAMPUS FARIA LIMA', 'ticker' => 'FCFL11'],
            ['name' => 'FDO INV IMOB - FII CENESP', 'ticker' => 'CNES11'],
            ['name' => 'FDO INV IMOB - FII CEO CYRELA COMMERC. PROPERTIES', 'ticker' => 'CEOC11'],
            ['name' => 'FDO INV IMOB - FII EDIFÍCIO ALMIRANTE BARROSO', 'ticker' => 'FAMB11'],
            ['name' => 'FDO INV IMOB - FII EDIFÍCIO GALERIA', 'ticker' => 'EDGA11'],
            ['name' => 'FDO INV IMOB - FII ELDORADO', 'ticker' => 'ELDO11'],
            ['name' => 'FDO INV IMOB - FII HOSPITAL DA CRIANÇA', 'ticker' => 'HCRI11'],
            ['name' => 'FDO INV IMOB - FII HOSPITAL NOSSA SRA DE LOURDES', 'ticker' => 'NSLU11'],
            ['name' => 'FDO INV IMOB - FII HOTEL MAXINVEST', 'ticker' => 'HTMX11'],
            ['name' => 'FDO INV IMOB - FII MAX RETAIL', 'ticker' => 'MAXR11'],
            ['name' => 'FDO INV IMOB - FII NCH BRASIL RECEBÍVEIS IMOB', 'ticker' => 'NCHB11'],
            ['name' => 'FDO INV IMOB - FII NOVO HORIZONTE', 'ticker' => 'NVHO11'],
            ['name' => 'FDO INV IMOB - FII PARQUE D. PEDRO SHOPPING CENTER', 'ticker' => 'PQDP11'],
            ['name' => 'FDO INV IMOB - FII PATEO BANDEIRANTES', 'ticker' => 'PATB11'],
            ['name' => 'FDO INV IMOB - FII RBR DESENVOLVIMENTO', 'ticker' => 'RBRM11'],
            ['name' => 'FDO INV IMOB - FII RBR RENDIMENTO HIGH GRADE', 'ticker' => 'RBRR11'],
            ['name' => 'FDO INV IMOB - FII REC RECEBIVEIS IMOBILIARIOS', 'ticker' => 'RECR11'],
            ['name' => 'FDO INV IMOB - FII REC RENDA IMOBILIARIA', 'ticker' => 'RECT11'],
            ['name' => 'FDO INV IMOB - FII SHOPPING PARQUE D. PEDRO', 'ticker' => 'SHDP11'],
            ['name' => 'FDO INV IMOB - FII SIA CORPORATE', 'ticker' => 'SAIC11'],
            ['name' => 'FDO INV IMOB - FII TORRE ALMIRANTE', 'ticker' => 'ALMI11'],
            ['name' => 'FDO INV IMOB - FII TORRE NORTE', 'ticker' => 'TRNT11'],
            ['name' => 'FDO INV IMOB - OURINVEST FUNDO DE FUNDOS', 'ticker' => 'OUFF11'],
            ['name' => 'FDO INV IMOB - OURINVEST RE I', 'ticker' => 'WTSP11'],
            ['name' => 'FDO INV IMOB - VBI LOGÍSTICO', 'ticker' => 'LVBI11'],
            ['name' => 'FDO INV IMOB BR HOTEIS - FII', 'ticker' => 'BRHT11'],
            ['name' => 'FDO INV IMOB BRASIL PLURAL ABSOLUTO FDO DE FUNDOS', 'ticker' => 'BPFF11'],
            ['name' => 'FDO INV IMOB BRASIL VAREJO - FII', 'ticker' => 'BVAR11'],
            ['name' => 'FDO INV IMOB BTG PACTUAL SHOPPINGS', 'ticker' => 'BPML11'],
            ['name' => 'FDO INV IMOB BTG PACTUAL TERRAS AGRÍCOLAS', 'ticker' => 'BTRA11'],
            ['name' => 'FDO INV IMOB CAIXA CARTEIRA IMOBILIÁRIA', 'ticker' => 'CXCI11'],
            ['name' => 'FDO INV IMOB CAIXA CEDAE', 'ticker' => 'CXCE11'],
            ['name' => 'FDO INV IMOB CAIXA SEQ LOGÍSTICA RENDA', 'ticker' => 'CXTL11'],
            ['name' => 'FDO INV IMOB CENTRO TEXTIL INTERNACIONAL', 'ticker' => 'CTXT11'],
            ['name' => 'FDO INV IMOB CJ - FII', 'ticker' => 'CJFI11'],
            ['name' => 'FDO INV IMOB CONTINENTAL SQUARE FARIA LIMA', 'ticker' => 'FLMA11'],
            ['name' => 'FDO INV IMOB EDIFÍCIO OURINVEST', 'ticker' => 'EDFO11'],
            ['name' => 'FDO INV IMOB EUROPAR', 'ticker' => 'EURO11'],
            ['name' => 'FDO INV IMOB GENERAL SEVERIANO - FII', 'ticker' => 'GESE11'],
            ['name' => 'FDO INV IMOB GRAND PLAZA SHOPPING', 'ticker' => 'ABCP11'],
            ['name' => 'FDO INV IMOB GREEN TOWERS', 'ticker' => 'GTWR11'],
            ['name' => 'FDO INV IMOB HABITAT I', 'ticker' => 'HBTT11'],
            ['name' => 'FDO INV IMOB HOSPITAL UNIMED CAMPINA GRANDE', 'ticker' => 'HUCG11'],
            ['name' => 'FDO INV IMOB HOSPITAL UNIMED SUL CAPIXABA', 'ticker' => 'HUSC11'],
            ['name' => 'FDO INV IMOB INDUSTRIAL DO BRASIL', 'ticker' => 'FIIB11'],
            ['name' => 'FDO INV IMOB INFRA REAL ESTATE - FII', 'ticker' => 'FINF11'],
            ['name' => 'FDO INV IMOB MEMORIAL OFFICE', 'ticker' => 'FMOF11'],
            ['name' => 'FDO INV IMOB MOGNO FUNDO DE FUNDOS', 'ticker' => 'MGFF11'],
            ['name' => 'FDO INV IMOB MV9 - FII', 'ticker' => 'MVFI11'],
            ['name' => 'FDO INV IMOB OURINVEST LOGÍSTICA', 'ticker' => 'OULG11'],
            ['name' => 'FDO INV IMOB PANAMBY', 'ticker' => 'PABY11'],
            ['name' => 'FDO INV IMOB PEDRA NEGRA RENDA IMOB', 'ticker' => 'FPNG11'],
            ['name' => 'FDO INV IMOB POLO ESTOQUE II - FII', 'ticker' => 'ESTQ11'],
            ['name' => 'FDO INV IMOB POLO SHOPPING INDAIATUBA', 'ticker' => 'VPSI11'],
            ['name' => 'FDO INV IMOB PROJETO ÁGUA BRANCA', 'ticker' => 'FPAB11'],
            ['name' => 'FDO INV IMOB RBR CREDITO IMOB ESTRUTURADO', 'ticker' => 'RBRY11'],
            ['name' => 'FDO INV IMOB RBR PROPERTIES - FII', 'ticker' => 'RBRP11'],
            ['name' => 'FDO INV IMOB RIO BRAVO RENDA CORPORATIVA', 'ticker' => 'RCRB11'],
            ['name' => 'FDO INV IMOB RIO BRAVO RENDA EDUCACIONAL - FII', 'ticker' => 'RBED11'],
            ['name' => 'FDO INV IMOB RIO BRAVO RENDA VAREJO - FII', 'ticker' => 'RBVA11'],
            ['name' => 'FDO INV IMOB RIO NEGRO - FII', 'ticker' => 'RNGO11'],
            ['name' => 'FDO INV IMOB SÃO FERNANDO', 'ticker' => 'SFND11'],
            ['name' => 'FDO INV IMOB SC 401', 'ticker' => 'FISC11'],
            ['name' => 'FDO INV IMOB SCP', 'ticker' => 'SCPF11'],
            ['name' => 'FDO INV IMOB SHOPPING PÁTIO HIGIENÓPOLIS', 'ticker' => 'SHPH11'],
            ['name' => 'FDO INV IMOB TG ATIVO REAL', 'ticker' => 'TGAR11'],
            ['name' => 'FDO INV IMOB THE ONE', 'ticker' => 'ONEF11'],
            ['name' => 'FDO INV IMOB VBI RENDIMENTOS IMOB I FII', 'ticker' => 'BARI11'],
            ['name' => 'FDO INV IMOB VEREDA - FII', 'ticker' => 'VERE11'],
            ['name' => 'FDO INV IMOB VIA PARQUE SHOPPING - FII', 'ticker' => 'FVPQ11'],
            ['name' => 'FDO INV IMOB VIDA NOVA - FII', 'ticker' => 'FIVN11'],
            ['name' => 'FDO INV IMOB VOTORANTIM LOGISTICA', 'ticker' => 'VTLT11'],
            ['name' => 'FDO INV IMOB VOTORANTIM SECURITIES', 'ticker' => 'VSEC11'],
            ['name' => 'FDO INV IMOB VOTORANTIM SHOPPING', 'ticker' => 'VSHO11'],
            ['name' => 'FDO INV IMOBILIÁRIO DE UNIDADES AUTÔNOMAS', 'ticker' => 'IDFI11'],
            ['name' => 'FDO INV. IMOB. PLURAL RECEBIVEIS', 'ticker' => 'PLCR11'],
            ['name' => 'FDO INV. IMOB. PLUS', 'ticker' => 'VTPL11'],
            ['name' => 'FDO INV. IMOB. REC LOGISTICA', 'ticker' => 'RELG11'],
            ['name' => 'FDO INV. IMOB. VBI CRI', 'ticker' => 'CVBI11'],
            ['name' => 'FDO INV. MAUA CAPITAL RECEBIVEIS IMOB. - FII', 'ticker' => 'MCCI11'],
            ['name' => 'FDO INVEST IMOB GRAND PLAZA MALL', 'ticker' => 'FGPM11'],
            ['name' => 'FDO. INV. IMOB. A - TOWN', 'ticker' => 'ATWN11'],
            ['name' => 'FDO. INV. IMOB. ÁTRIO REIT RECEBÍVEIS IMOBILIÁRIOS', 'ticker' => 'ARRI11'],
            ['name' => 'FDO. INV. IMOB. BTG PACTUAL AGRO LOGÍSTICA', 'ticker' => 'BTAL11'],
            ['name' => 'FDO. INV. IMOB. CAIXA IMÓVEIS CORPORATIVOS', 'ticker' => 'CXCO11'],
            ['name' => 'FDO. INV. IMOB. HOUSI', 'ticker' => 'HOSI11'],
            ['name' => 'FDO. INV. IMOB. MOGNO HOTEIS', 'ticker' => 'MGHT11'],
            ['name' => 'FDO. INV. IMOB. REC FUNDO DE FUNDOS', 'ticker' => 'RECX11'],
            ['name' => 'FDO. INV. IMOB. VBI PRIME PROPERTIES', 'ticker' => 'PVBI11'],
            ['name' => 'FDO. INVEST. IMOB. DEVANT FOF IMOBILIÁRIOS', 'ticker' => 'DVFF11'],
            ['name' => 'FDO. INVEST. IMOB. RB CAPITAL I FUNDO DE FUNDOS', 'ticker' => 'RFOF11'],
            ['name' => 'FDO. INVEST. IMOB. VOTORANTIM PATRIMONIAL V', 'ticker' => 'VTPA11'],
            ['name' => 'FDO. INVEST. IMOB. VOTORANTIM PATRIMONIAL XII', 'ticker' => 'VTXI11'],
            ['name' => 'FDO.INVEST. IMOB. MULTI RENDA URBANA', 'ticker' => 'HBRH11'],
            ['name' => 'FII BTG PACTUAL CRÉDITO IMOBILIÁRIO', 'ticker' => 'BTCI11'],
            ['name' => 'FII CENTRAL LEBLON - FDO INV IMOB', 'ticker' => 'CCLB11'],
            ['name' => 'FII HIRE RESIDENCIAL I - FDO DE INV IMOB', 'ticker' => 'HRES11'],
            ['name' => 'FII IRIDIUM RECEBÍVEIS IMOBILIÁRIOS', 'ticker' => 'IRDM11'],
            ['name' => 'FRAM CAPITAL SBCLOG FDO. INV. IMOB.', 'ticker' => 'SBCL11'],
            ['name' => 'FRONTEIRA MULTI FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'FRHY11'],
            ['name' => 'FUND. INVEST. IMOB. SUCCESPAR VAREJO', 'ticker' => 'SPVJ11'],
            ['name' => 'FUNDO DE FDO INV IMOB KINEA FII', 'ticker' => 'KFOF11'],
            ['name' => 'FUNDO DE INVEST IMOB OURINVEST RENDA ESTRUTURADA', 'ticker' => 'OURE11'],
            ['name' => 'FUNDO DE INVEST IMOBILIARIO SUNO ENERGIAS LIMPAS', 'ticker' => 'SNEL11'],
            ['name' => 'FUNDO DE INVESTIMENTO IMOBILIÁRIO - BLUE RECEBÍVEI', 'ticker' => 'BLUR11'],
            ['name' => 'FUNDO DE INVESTIMENTO IMOBILIÁRIO - DEVELOPMENT V1', 'ticker' => 'LKDV11'],
            ['name' => 'FUNDO DE INVESTIMENTO IMOBILIÁRIO - FII RBR DESENV', 'ticker' => 'RBRI11'],
            ['name' => 'FUNDO DE INVESTIMENTO IMOBILIÁRIO - SPX SYN MULT', 'ticker' => 'SPXS11'],
            ['name' => 'FUNDO DE INVESTIMENTO IMOBILIÁRIO - VBI GREENPOWER', 'ticker' => 'GVBI11'],
            ['name' => 'FUNDO DE INVESTIMENTO IMOBILIÁRIO APEX MALLS - FII', 'ticker' => 'APXM11'],
            ['name' => 'FUNDO DE INVESTIMENTO IMOBILIÁRIO BRL PROP II', 'ticker' => 'BRLA11'],
            ['name' => 'FUNDO DE INVESTIMENTO IMOBILIÁRIO CAIXA AGÊNCIAS', 'ticker' => 'CXAG11'],
            ['name' => 'FUNDO DE INVESTIMENTO IMOBILIÁRIO HBC RENDA URBANA', 'ticker' => 'HBCR11'],
            ['name' => 'FUNDO DE INVESTIMENTO IMOBILIÁRIO MINT EDUCACIONAL', 'ticker' => 'MINT11'],
            ['name' => 'FUNDO DE INVESTIMENTO IMOBILIARIO PATRIMONIAL IV', 'ticker' => 'OPTM11'],
            ['name' => 'FUNDO DE INVESTIMENTO IMOBILIÁRIO RIZA TERRAX', 'ticker' => 'RZTR11'],
            ['name' => 'FUNDO DE INVESTIMENTO IMOBILIÁRIO ROOFTOP I', 'ticker' => 'ROOF11'],
            ['name' => 'G5 CIDADE NOVA FDO. INVEST. IMOB.', 'ticker' => 'TCIN11'],
            ['name' => 'GALAPAGOS RECEBÍVEIS IMOBILIÁRIOS - FDO. INV. IMOB', 'ticker' => 'GCRI11'],
            ['name' => 'GALAPAGOS SPECIAL OPORTUNITIES FII', 'ticker' => 'GCOI11'],
            ['name' => 'GAZIT MALLS FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'GZIT11'],
            ['name' => 'GENERAL SHOP E OUTLETS DO BRASIL FDO INV IMOB - FI', 'ticker' => 'GSFI11'],
            ['name' => 'GENERAL SHOPPING ATIVO E RENDA FUNDO DE INV, IMOB.', 'ticker' => 'FIGS11'],
            ['name' => 'GENIAL LOGÍSTICA FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'GLOG11'],
            ['name' => 'GENIAL RENDA URBANA FDO DE INV IMOB', 'ticker' => 'GURB11'],
            ['name' => 'GGR COVEPI RENDA FDO INV IMOB', 'ticker' => 'GGRC11'],
            ['name' => 'GRUPO RCFA FDO INV IMOB', 'ticker' => 'RCFA11'],
            ['name' => 'GTIS BRAZIL LOGISTICS FDO. INV. IMOB.', 'ticker' => 'GTLG11'],
            ['name' => 'GUARDIAN LOGISTICA FDO. INVEST. IMOB.', 'ticker' => 'GALG11'],
            ['name' => 'HABITAT II - FDO INV IMOB', 'ticker' => 'HABT11'],
            ['name' => 'HAZ FDO INV IMOB - FII', 'ticker' => 'ATCR11'],
            ['name' => 'HECTARE CE - FDO INV IMOB', 'ticker' => 'HCTR11'],
            ['name' => 'HECTARE DESENV. STUDENT HOUSING - FDO. INV. IMOB.', 'ticker' => 'HCST11'],
            ['name' => 'HECTARE RECEBÍVEIS HIGH GRADE FDO. INV. IMOB.', 'ticker' => 'HCHG11'],
            ['name' => 'HEDGE AAA FDO. INV. IMOB.', 'ticker' => 'HAAA11'],
            ['name' => 'HEDGE ATRIUM SHOPPING SANTO ANDRE FDO INV IMOB', 'ticker' => 'ATSA11'],
            ['name' => 'HEDGE BRASIL SHOPPING FDO INV IMOB', 'ticker' => 'HGBS11'],
            ['name' => 'HEDGE DESENVOLVIMENTO LOGÍSTICO FDO INV IMOB', 'ticker' => 'HDEL11'],
            ['name' => 'HEDGE FLORIPA SHOPPING FUNDO INV IMOBI', 'ticker' => 'FLRP11'],
            ['name' => 'HEDGE LOGÍSTICA FDO. INV. IMOB.', 'ticker' => 'HLOG11'],
            ['name' => 'HEDGE OFFICE INCOME FUNDO DE INVESTIMENTO IMOB.', 'ticker' => 'HOFC11'],
            ['name' => 'HEDGE PALADIN DESIGN OFFICES FDO INV IMOB', 'ticker' => 'HDOF11'],
            ['name' => 'HEDGE REALTY DEVELOPMENT FDO INV IMOB', 'ticker' => 'HRDF11'],
            ['name' => 'HEDGE RECEBIVEIS IMOB. FUNDO DE INVST. IMOB.', 'ticker' => 'HREC11'],
            ['name' => 'HEDGE SEED FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'SEED11'],
            ['name' => 'HEDGE SHOPPING PARQUE DOM PEDRO FDO. DE INV. IMOB.', 'ticker' => 'HPDP11'],
            ['name' => 'HEDGE TOP FOFII 3 FDO INV IMOB', 'ticker' => 'HFOF11'],
            ['name' => 'HGI CRÉDITOS IMOBILIÁRIOS FDO. INV. IMOB.', 'ticker' => 'HGIC11'],
            ['name' => 'HIRE LOG I FDO DE INV IMOB', 'ticker' => 'HILG11'],
            ['name' => 'HSI ATIVOS FINANCEIROS FUNDO DE INVESTIMENTO IMOBI', 'ticker' => 'HSAF11'],
            ['name' => 'HSI LOGÍSTICA FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'HSLG11'],
            ['name' => 'HSI MALL FDO INV IMOB', 'ticker' => 'HSML11'],
            ['name' => 'HSI RENDA IMOB FDO INV IMOB', 'ticker' => 'HSRE11'],
            ['name' => 'HUSI FDO INV. IMOB.', 'ticker' => 'HUSI11'],
            ['name' => 'INTER TEVA INDICE DE PAPEL FUNDO DE INVESTIMENTO', 'ticker' => 'ITIP11'],
            ['name' => 'INTER TÍTULOS IMOB. FDO INV. IMOB.', 'ticker' => 'BICR11'],
            ['name' => 'IRIDIUM FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'IRIM11'],
            ['name' => 'ITAÚ CRÉDITO IMOB IPCA FDO DE INV IMOB', 'ticker' => 'ICRI11'],
            ['name' => 'ITAÚ TEMPUS FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'TMPS11'],
            ['name' => 'JACARANDÁ 02 FUNDO DE INVESTIMENTO IMOBILIÁRIO FII', 'ticker' => 'JCDB11'],
            ['name' => 'JACARANDÁ I FUNDO DE INVESTIMENTO IMOBILIÁRIO -FII', 'ticker' => 'JCDA11'],
            ['name' => 'JBFO FOF FDO INV. IMOB.', 'ticker' => 'JBFO11'],
            ['name' => 'JFDCAM FUNDO DE INVESTIMENTO IMOBILIÁRIO FII', 'ticker' => 'VJFD11'],
            ['name' => 'JFL LIVING FDO. INV. IMOB.', 'ticker' => 'JFLL11'],
            ['name' => 'JHSF CAPITAL CIDADE JARDIM - FDO DE INV IMOB', 'ticker' => 'JCCJ11'],
            ['name' => 'JPP CAPITAL FDO INV IMOB - FII', 'ticker' => 'JPPC11'],
            ['name' => 'JPP CAPITAL RECEBIVEIS IMOB. FDO. INVEST. IMOB.', 'ticker' => 'JPPA11'],
            ['name' => 'JS ATIVOS FINANCEIROS FDO DE INV IMOBILIÁRIO', 'ticker' => 'JSAF11'],
            ['name' => 'JS REAL ESTATE MULTIGESTÃO - FII', 'ticker' => 'JSRE11'],
            ['name' => 'JT PREV FDO INV IMOB DESENVOLVIMENTO HABITACIONAL', 'ticker' => 'JTPR11'],
            ['name' => 'KILIMA FIC FDO. IMOB. SUNO 30', 'ticker' => 'KISU11'],
            ['name' => 'KILIMA VOLKANO RECEBÍVEIS IMOB FDO DE INV IMOB', 'ticker' => 'KIVO11'],
            ['name' => 'KINEA CREDITAS FDO DE INV IMOBILIÁRIO - FII', 'ticker' => 'KCRE11'],
            ['name' => 'KINEA DESENVOLVIMENTO LOGÍSTICO FDO DE INV IMOB', 'ticker' => 'KLOG11'],
            ['name' => 'KINEA HEDGE FUND FDO DE INV IMOB', 'ticker' => 'KNHF11'],
            ['name' => 'KINEA HIGH YIELD CRI FDO INV IMOB - FII', 'ticker' => 'KNHY11'],
            ['name' => 'KINEA II REAL ESTATE EQUITY FDO INV IMOB', 'ticker' => 'KNRE11'],
            ['name' => 'KINEA ÍNDICES DE PREÇOS FDO INV IMOB - FII', 'ticker' => 'KNIP11'],
            ['name' => 'KINEA PREMIUM PROPERTIES FDO INV IMOB', 'ticker' => 'KNPR11'],
            ['name' => 'KINEA RENDA IMOBILIÁRIA FDO INV IMOB - FII', 'ticker' => 'KNRI11'],
            ['name' => 'KINEA RENDIMENTOS IMOBILIÁRIOS FDO INV IMOB - FII', 'ticker' => 'KNCR11'],
            ['name' => 'KINEA SECURITIES FDO. DE INV. IMOB. - FII', 'ticker' => 'KNSC11'],
            ['name' => 'KINEA UNIQUE HY CDI FUNDO DE INVESTIMENTO IMOB', 'ticker' => 'KNUQ11'],
            ['name' => 'LAGO DA PEDRA - FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'LPLP11'],
            ['name' => 'LAV SLDZ DESENVOLVIMENTO IMOB FDO INV IMOB', 'ticker' => 'SLDZ11'],
            ['name' => 'LEGATUS SHOPPINGS FDO. INV. IMOB. - FII', 'ticker' => 'LASC11'],
            ['name' => 'LESTE RIVA EQUITY PREFERENCIAL I FDO. INV. IMOB.', 'ticker' => 'LSPA11'],
            ['name' => 'LIFE CAPITAL PARTNERS FUNDO DE INVESTIMENTO IMOB', 'ticker' => 'LIFE11'],
            ['name' => 'LOFT I - FDO INV IMOB', 'ticker' => 'LOFT11'],
            ['name' => 'LOFT II FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'LFTT11'],
            ['name' => 'LOGCP INTER FDO INV IMOB', 'ticker' => 'LGCP11'],
            ['name' => 'LUGGO FDO. INV. IMOB.', 'ticker' => 'LUGG11'],
            ['name' => 'MALLS BRASIL PLURAL FDO INV IMOB', 'ticker' => 'MALL11'],
            ['name' => 'MANATÍ CAPITAL HEDGE FUND FDO INV IMOB', 'ticker' => 'MANA11'],
            ['name' => 'MARESIAS FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'MMVE11'],
            ['name' => 'MAUÁ CAPITAL HEDGE FUND - FDO. INVEST. IMOB.', 'ticker' => 'MCHF11'],
            ['name' => 'MAXI RENDA FDO INV IMOB - FII', 'ticker' => 'MXRF11'],
            ['name' => 'MÉRITO DESENVOLVIMENTO IMOBILIÁRIO I FII - FII', 'ticker' => 'MFII11'],
            ['name' => 'MERITO FDO. AÇÕES IMOB. FII - FDO INV. IMOB.', 'ticker' => 'MFAI11'],
            ['name' => 'MÉRITO RECEBÍVEIS IMOBILIÁRIOS FII - FDO INV IMOB', 'ticker' => 'MFCR11'],
            ['name' => 'MOGNO PROPERTIES FUNDO DE INVESTIMENTO IMOBILIARIO', 'ticker' => 'MGRI11'],
            ['name' => 'MORE REAL ESTATE FOF FII FDO. INV. IMOB.', 'ticker' => 'MORE11'],
            ['name' => 'MORE RECEBÍVEIS IMOBILIÁRIOS FII FDO. INV. IMOB.', 'ticker' => 'MORC11'],
            ['name' => 'MULTI SHOPPINGS FDO INV IMOB - FII', 'ticker' => 'SHOP11'],
            ['name' => 'MULTIGESTÃO RENDA COMERCIAL FDO INV IMOB - FII', 'ticker' => 'DRIT11'],
            ['name' => 'MULTIOFFICES 2 - FDO. INV. IMOB.', 'ticker' => 'MOFF11'],
            ['name' => 'NAVI CRÉDITO IMOBILIÁRIO - FDO INV IMOB', 'ticker' => 'NCRI11'],
            ['name' => 'NAVI IMOBILIÁRIO TOTAL RETURN FDO. INVEST. IMOB.', 'ticker' => 'NAVT11'],
            ['name' => 'NAVI RESIDENCIAL FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'APTO11'],
            ['name' => 'NEWPORT LOGÍSTICA FDO INV. IMOB.', 'ticker' => 'NEWL11'],
            ['name' => 'NEWPORT RENDA URBANA FDO INV IMOB', 'ticker' => 'NEWU11'],
            ['name' => 'NOVA I - FDO INV IMOB - FII', 'ticker' => 'NVIF11'],
            ['name' => 'OCTO FDO DE INV IMOB', 'ticker' => 'OCRE11'],
            ['name' => 'OPPORTUNITY BALASSIANO FDO DE INV IMOB', 'ticker' => 'OBAL11'],
            ['name' => 'OPPORTUNITY FDO INV IMOB', 'ticker' => 'FTCE11'],
            ['name' => 'ÓRAMA HIGH YIELD FDO INV IMOB', 'ticker' => 'OGHY11'],
            ['name' => 'OURINVEST JPP FDO INV IMOB - FII', 'ticker' => 'OUJP11'],
            ['name' => 'PANORAMA CREDITO RESIDENCIAL FDO DE INV IMOB', 'ticker' => 'PNCR11'],
            ['name' => 'PANORAMA DESENVOLVIMENTO LOGÍSTICO FDO. INV. IMOB.', 'ticker' => 'PNDL11'],
            ['name' => 'PANORAMA LAST MILE SBC FDO INV IMOB', 'ticker' => 'PNLM11'],
            ['name' => 'PANORAMA PROPERTIES FDO. INVEST. IMOB.', 'ticker' => 'PNPR11'],
            ['name' => 'PANORAMA REAL ESTATE CRÉDITO FDO INV IMOB', 'ticker' => 'PNRC11'],
            ['name' => 'PARAMIS HEDGE FUND FDO DE INV IMOB', 'ticker' => 'PMIS11'],
            ['name' => 'PARKING PARTNERS FDO. INVEST. IMOB.', 'ticker' => 'VTVI11'],
            ['name' => 'PARQUE ANHANGUERA FDO. INVEST. IMOB.', 'ticker' => 'PQAG11'],
            ['name' => 'PÁTRIA EDIFÍCIOS CORPORATIVOS FDO INV IMOB - FII', 'ticker' => 'PATC11'],
            ['name' => 'PÁTRIA LOGÍSTICA FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'PATL11'],
            ['name' => 'PERFORMA REAL ESTATE - FDO. INV. IMOB.', 'ticker' => 'PEMA11'],
            ['name' => 'PERSONALE I FDO INV IMOB - FII', 'ticker' => 'PRSN11'],
            ['name' => 'POLO CREDITO IMOBILIARIO- FII', 'ticker' => 'PORD11'],
            ['name' => 'POLO FDO INV IMOB - FII RECEBÍVEIS IMOBILIÁRIOS I', 'ticker' => 'PLRI11'],
            ['name' => 'PRAIA DO CASTELO FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'PCAS11'],
            ['name' => 'PRAZO - FUNDO DE INVESTIMENTO IMOBILIÁRIO - FII', 'ticker' => 'PRZS11'],
            ['name' => 'PRESIDENTE VARGAS FDO INV IMOB', 'ticker' => 'PRSV11'],
            ['name' => 'PROLOGIS BRAZIL LOGISTICS VENTURE FDO INV IMOB', 'ticker' => 'PBLV11'],
            ['name' => 'QUASAR AGRO - FDO INV. IMOB.', 'ticker' => 'QAGR11'],
            ['name' => 'QUASAR CRÉDITO IMOBILIÁRIO FDO. INV. IMOB.', 'ticker' => 'QAMI11'],
            ['name' => 'R CAP 1810 FUNDO DE FUNDOS - FDO. INV. IMOB.', 'ticker' => 'XBXO11'],
            ['name' => 'RB CAPITAL DESENV RESID III FDO INV IMOB - FII', 'ticker' => 'RSPD11'],
            ['name' => 'RB CAPITAL DESENV. RESID. II FDO INV IMOB - FII', 'ticker' => 'RBDS11'],
            ['name' => 'RB CAPITAL DESENV. RESIDENCIAL IV FDO. INV. IMOB.', 'ticker' => 'RBIR11'],
            ['name' => 'RB CAPITAL LOGÍSTICO FDO. INV. IMOB.ye', 'ticker' => 'RBLG11'],
            ['name' => 'RB CAPITAL RECEBÍVEIS IMOB. FDO. INVEST. IMOB FII', 'ticker' => 'RRCI11'],
            ['name' => 'RB CAPITAL RENDA I FDO INV IMOB - FII', 'ticker' => 'FIIP11'],
            ['name' => 'RB CAPITAL RENDA II FDO INV IMOB - FII', 'ticker' => 'RBRD11'],
            ['name' => 'RB CAPITAL TFO SITUS FDO INV IMOB - FII', 'ticker' => 'RBTS11'],
            ['name' => 'RBR ALPHA MULTIESTRATÉGIA REAL ESTATE FDO INV IMOB', 'ticker' => 'RBRF11'],
            ['name' => 'RBR CRI - FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'CCRF11'],
            ['name' => 'RBR DESENV COMERCIAL FEEDER FOF FDO INVEST IMOB', 'ticker' => 'RCFF11'],
            ['name' => 'RBR LOG FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'RBRL11'],
            ['name' => 'RBR PLUS MULTIESTRATÉGIA REAL ESTATE FII', 'ticker' => 'RBRX11'],
            ['name' => 'RBR PREMIUM RECEBÍVEIS IMOBILIÁRIOS FDO INV IMOB', 'ticker' => 'RPRI11'],
            ['name' => 'REAG MULTI ATIVOS IMOBILIÁRIOS - FII', 'ticker' => 'RMAI11'],
            ['name' => 'REAL INVESTOR FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'RINV11'],
            ['name' => 'RESIDENCIAIS ONE FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'REON11'],
            ['name' => 'RIO BRAVO CREDITO IMOB HIGH GRADE FUND DE INVEST', 'ticker' => 'RBHG11'],
            ['name' => 'RIO BRAVO CRÉDITO IMOB. HIGH YIELD FDO. INV. IMOB.', 'ticker' => 'RBHY11'],
            ['name' => 'RIO BRAVO CRÉDITO IMOBILIÁRIO II FDO INV IMOB -FII', 'ticker' => 'RBVO11'],
            ['name' => 'RIO BRAVO FUNDO DE FUNDOS DE INVESTIMENTO IMOB', 'ticker' => 'RBFF11'],
            ['name' => 'RIO BRAVO OPORTUNIDADES IMOBILIÁRIAS FII', 'ticker' => 'RBOP11'],
            ['name' => 'RIO BRAVO RENDA RESIDENCIAL FDO. INVEST. IMOB.', 'ticker' => 'RBRS11'],
            ['name' => 'RIZA AKIN FDO. INV. IMOB. FII', 'ticker' => 'RZAK11'],
            ['name' => 'RIZA ARCTIUM REAL ESTATE FDO INV IMOB', 'ticker' => 'RZAT11'],
            ['name' => 'RIZA MEYENII ATIVOS REAIS DEDICADO - FDO INV IMOB', 'ticker' => 'MYDW11'],
            ['name' => 'ROCK - FII FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'RCKF11'],
            ['name' => 'SANTANDER PAPEIS IMOB CDI FDO INV IMOB', 'ticker' => 'SADI11'],
            ['name' => 'SANTANDER PAPÉIS IMOBILIÁRIOS FDO DE INV IMOB', 'ticker' => 'SAPI11'],
            ['name' => 'SANTANDER RENDA DE ALUGUÉIS FDO. INVEST. IMOB.', 'ticker' => 'SARE11'],
            ['name' => 'SÃO CARLOS RENDA IMOBILIÁRIA FDO. INV. IMOB.', 'ticker' => 'SACL11'],
            ['name' => 'SAO DOMINGOS FDO INV IMOB - FII', 'ticker' => 'FISD11'],
            ['name' => 'SEQUOIA III RENDA IMOBILIÁRIA - FDO. INV. IMOB.', 'ticker' => 'SEQR11'],
            ['name' => 'SH SPECIAL OPPS FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'SHSO11'],
            ['name' => 'SHOPPING WEST PLAZA FDO INV IMOB', 'ticker' => 'WPLZ11'],
            ['name' => 'SHOPPINGS AAA FDO DE INV IMOB', 'ticker' => 'CPSH11'],
            ['name' => 'SIG CAPITAL RECEBÍVEIS PULVERIZADOS FDO INV IMOB', 'ticker' => 'SIGR11'],
            ['name' => 'SINGULARE FDO INV IMOB - FII', 'ticker' => 'REIT11'],
            ['name' => 'SJ AU LOGÍSTICA FDO. INV. IMOB.', 'ticker' => 'SJAU11'],
            ['name' => 'SOLARIUM FII - FDO INV. IMOB.', 'ticker' => 'SOLR11'],
            ['name' => 'SP DOWNTOWN FDO INV IMOB - FII', 'ticker' => 'SPTW11'],
            ['name' => 'SPA FDO INV IMOB - FII', 'ticker' => 'SPAF11'],
            ['name' => 'SPECIALE BLUE REAL ASSET FDO DE INV IMOB', 'ticker' => 'LTMT11'],
            ['name' => 'SPECIALE REAL ESTATE FUND OF FUNDS FDO DE INV IMOB', 'ticker' => 'PMFO11'],
            ['name' => 'STARX FDO INV IMOB - FII', 'ticker' => 'STRX11'],
            ['name' => 'SUNO FUNDO DE FUNDOS DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'SNFF11'],
            ['name' => 'SUNO LOG FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'SNLG11'],
            ['name' => 'SUNO RECEBÍVEIS IMOBILIÁRIOS FDO DE INV IMOB', 'ticker' => 'SNCI11'],
            ['name' => 'SUPREMO FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'SPMO11'],
            ['name' => 'TELLUS DESENVOLVIMENTO LOGÍSTICO FDO. INVEST. IMOB', 'ticker' => 'TELD11'],
            ['name' => 'TELLUS MULTIESTRATÉGIA - FDO INV IMOB', 'ticker' => 'TELM11'],
            ['name' => 'TELLUS PROPERTIES - FDO INV. IMOB', 'ticker' => 'TEPP11'],
            ['name' => 'TISHMAN SPEYER RENDA CORPORATIVA FDO. INV. IMOB.', 'ticker' => 'TSER11'],
            ['name' => 'TJK RENDA IMOBILIÁRIA FDO INV IMOB', 'ticker' => 'TJKB11'],
            ['name' => 'TORDESILHAS EI FDO. INV. IMOB.', 'ticker' => 'TORD11'],
            ['name' => 'TRANSINC FDO INV IMOB - FII', 'ticker' => 'TSNC11'],
            ['name' => 'TREECORP REAL ESTATE FDO INV IMOB - I', 'ticker' => 'TCPF11'],
            ['name' => 'TRX REAL ESTATE FDO. INV. IMOB. - FII', 'ticker' => 'TRXF11'],
            ['name' => 'TRX REAL ESTATE II FDO. INVEST. IMOB.', 'ticker' => 'TRXB11'],
            ['name' => 'URCA PRIME RENDA FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'URPR11'],
            ['name' => 'V2 EDIFICIOS CORPORATIVOS FDO INV IMOB - FII', 'ticker' => 'VVCO11'],
            ['name' => 'V2 RECEBÍVEIS IMOBILIÁRIOS FUNDO DE INVESTIMENTO I', 'ticker' => 'VVCR11'],
            ['name' => 'V2 RENDA IMOBILIÁRIA FDO DE INV IMOB', 'ticker' => 'VVRI11'],
            ['name' => 'VALORA CRI CDI FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'VGIR11'],
            ['name' => 'VALORA CRI ÍNDICE DE PREÇO FDO INVEST. IMOB. FII', 'ticker' => 'VGIP11'],
            ['name' => 'VALORA HEDGE FUND FDO. INV. IMOB.', 'ticker' => 'VGHF11'],
            ['name' => 'VBI CONSUMO ESSEN FDO. INVEST. IMOB.', 'ticker' => 'EVBI11'],
            ['name' => 'VBI CRÉDITO IMOBILIÁRIO - FDO. INV. IMOB.', 'ticker' => 'BLMC11'],
            ['name' => 'VBI OFFICE FUND II - FDO. INVEST. IMOB.', 'ticker' => 'BLMO11'],
            ['name' => 'VBI REITS FOF - FDO. INV. IMOB', 'ticker' => 'RVBI11'],
            ['name' => 'VBI RENDA + FOF FDO. INVEST. IMOB.', 'ticker' => 'BLMR11'],
            ['name' => 'VBI TR FARIA LIMA 4440 FII', 'ticker' => 'FLFL11'],
            ['name' => 'VECTIS JUROS REAL FDO INV. IMOB. - FII', 'ticker' => 'VCJR11'],
            ['name' => 'VECTIS RENDA RESIDENCIAL FDO. INV. IMOB.', 'ticker' => 'VCRR11'],
            ['name' => 'VECTOR QUELUZ ATIVOS IMOB FDO INV IMOB', 'ticker' => 'VLJS11'],
            ['name' => 'VENUS - FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'SALI11'],
            ['name' => 'VERSALHES RECEBÍVEIS IMOBILIÁRIOS - FDO. INV. IMOB', 'ticker' => 'VSLH11'],
            ['name' => 'VIC DESENVOLVIMENTO VINTAGE 20/21 FUND INVEST IMOB', 'ticker' => 'VIDS11'],
            ['name' => 'VIC DESENVOLVIMENTO VINTAGE 22/23 FDO DE INV IMOB', 'ticker' => 'VDSV11'],
            ['name' => 'VINCI CREDIT SECURITIES FUNDO DE INVESTIMENTO IMOB', 'ticker' => 'VCRI11'],
            ['name' => 'VINCI IMÓVEIS URBANOS FDO. DE INV. IMOB.', 'ticker' => 'VIUR11'],
            ['name' => 'VINCI INSTRUMENTOS FINANCEIROS FDO INV IMOB - FII', 'ticker' => 'VIFI11'],
            ['name' => 'VINCI LOGÍSTICA FDO INV IMOB - FII', 'ticker' => 'VILG11'],
            ['name' => 'VINCI OFFICES FDO INV IMOB', 'ticker' => 'VINO11'],
            ['name' => 'VINCI SHOPPING CENTERS FDO INVEST IMOB - FII', 'ticker' => 'VISC11'],
            ['name' => 'VOTORANTIM SECURITIES MASTER FDO INV IMOB - FII', 'ticker' => 'VOTS11'],
            ['name' => 'VX XVI - FDO INV. IMOB.', 'ticker' => 'VXXV11'],
            ['name' => 'WARREN SECURITIES FDO DE INV IMOB - FII', 'ticker' => 'WSEC11'],
            ['name' => 'WHG FINVEST SP REALTY FDO DE INV IMOB - FII', 'ticker' => 'SPDE11'],
            ['name' => 'WHG REAL ESTATE FUNDO DE INVESTIMENTO IMOBILIÁRIO', 'ticker' => 'WHGR11'],
            ['name' => 'XP CORPORATE MACAÉ FDO INV IMOB - FII', 'ticker' => 'XPCM11'],
            ['name' => 'XP CREDITO IMOBILIÁRIO - FDO INV IMOB', 'ticker' => 'XPCI11'],
            ['name' => 'XP INDUSTRIAL FDO INV IMOB - FII', 'ticker' => 'XPIN11'],
            ['name' => 'XP LOG FDO INV IMOB - FII', 'ticker' => 'XPLG11'],
            ['name' => 'XP MALLS FDO INV IMOB FII', 'ticker' => 'XPML11'],
            ['name' => 'XP PROPERTIES FDO. INV. IMOB.', 'ticker' => 'XPPR11'],
            ['name' => 'XP SELECTION FDO DE FUNDOS INV IMOB - FII', 'ticker' => 'XPSF11'],
            ['name' => 'YUCA FDO INV. IMOB.', 'ticker' => 'YUFI11'],
            ['name' => 'ZAVIT CRÉDITO IMOBILIÁRIO - FDO INV IMOB', 'ticker' => 'ZAVC11'],
            ['name' => 'ZAVIT REAL ESTATE FUND - FDO INV IMOB', 'ticker' => 'ZAVI11'],
            ['name' => 'ZION CAPITAL FUNDO DE INVESTIMENTO IMOBILIÁRIO FII', 'ticker' => 'ZIFI11']
        ];
    }
}
